### ISSUE TITLE
win尝试编译了半天没成，哪位老哥指点下哈？

### ISSUE THREAD

**Issue by frustreated** [xjasonlyu/tun2socks#10]
如题

**Comment by xjasonlyu** [comment]
报啥错啊？要cgo环境的。
这个建议拿来做代理网关用，没有win优化的

**Comment by frustreated** [comment]
> 报啥错啊？要cgo环境的。
> 这个建议拿来做代理网关用，没有win优化的

谢谢老哥回应，明天回去重新做做，万一搞成了我总结下。这个非常喜欢的，我看netch貌似用的这个。

**Comment by frustreated** [comment]
> 报啥错啊？要cgo环境的。
> 这个建议拿来做代理网关用，没有win优化的

试过了，编译成了。用起来很6。平时用全局比较多，感觉这个很OK

**Comment by frustreated** [comment]
> 报啥错啊？要cgo环境的。
> 这个建议拿来做代理网关用，没有win优化的

试过了，编译成了。用起来很6。平时用全局比较多，感觉这个很OK
