### ISSUE TITLE
[Bug] 使用并发测试，然后关闭程序之后，连接状态还一直保存存在，并没及时释放

### ISSUE THREAD

**Issue by f4nff** [xjasonlyu/tun2socks#100]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

https://github.com/xjasonlyu/tun2socks/commit/5679d15442382478f295bd5c02025f562efa6bb6

### Description

`./stress -n -1 -c 1000 -m POST https://www.google.com/`

C:\Users\ll>nslookup www.google.com
服务器:  UnKnown
Address:  10.10.1.1

非权威应答:
名称:    www.google.com
Addresses:  2607:f8b0:4007:810::2004
          142.250.68.36

![image](https://user-images.githubusercontent.com/19538878/153739601-4e4d7550-6fcd-46d6-8852-6dfc5236ee14.png)

我使用并发测试，然后关闭程序之后，连接状态还一直保存存在，并没释放。
已经把程序关闭了，tcp状态在本地已经没了，

通过conntrack命令行工具查看conntrack的内容

```
yum install -y conntrack  
conntrack -L  
```
正常的流程应该tun发现连接断开之后，主动断开socks5的连接吧，

**Comment by xjasonlyu** [comment]
我又试了一下，是都能双向close的。你要不提供一下完整的`netstat -a`信息看看。

**Comment by f4nff** [comment]
你是本地测试，还是丢在路由器上测的？
我测试了，也会释放，但是释放周期很长，

**Comment by f4nff** [comment]
就是判断tcpwaitout这个时间，你怎么判断的，

**Comment by xjasonlyu** [comment]
> 就是判断tcpwaitout这个时间，你怎么判断的

这个参数5秒，和这个问题联系不大。

然后你是完整跑完整个stress，还是跑到一半忽然关掉的？

**Comment by f4nff** [comment]
跑到一半直接结束进程，

**Comment by xjasonlyu** [comment]
> 跑到一半直接结束进程，

那就是了，你进程跑到一半忽然关了所以你那侧没有主动发送FIN，然后tun2socks不知道你关了加上又开了tcp keepalive，所以只能等idleTimeout到了然后每一个interval发送共count个存活包等你ack，最后你什么响应都没有才会断开连接。这是正常的TCP机制，不是BUG。

**Comment by f4nff** [comment]
系统默认的interval  count  keepalive 周期太长了，tun2socks能不能也实现一套类似的机制，把超时的周期缩短点，
有时候不方便修改系统本身的。

**Comment by xjasonlyu** [comment]
```text
tcp_keepalive_intvl (integer; default: 75; since Linux 2.4)
      The number of seconds between TCP keep-alive probes.

tcp_keepalive_probes (integer; default: 9; since Linux 2.2)
      The maximum number of TCP keep-alive probes to send before
      giving up and killing the connection if no response is
      obtained from the other end.

tcp_keepalive_time (integer; default: 7200; since Linux 2.2)
      The number of seconds a connection needs to be idle before
      TCP begins sending out keep-alive probes.  Keep-alives are
      sent only when the SO_KEEPALIVE socket option is enabled.
      The default value is 7200 seconds (2 hours).  An idle
      connection is terminated after approximately an additional
      11 minutes (9 probes an interval of 75 seconds apart) when
      keep-alive is enabled.

      Note that underlying connection tracking mechanisms and
      application timeouts may be much shorter.
```

tun2socks使用的是独立的userspace netstack（gVisor），修改linux内核参数也没有效果。gVisor默认使用的linux参数，在tun2socks里已经调小了很多，把整体超时时间控制在5分钟左右了，原本是要2个多小时才会释放的：

```
// tcpKeepaliveIdle specifies the time a connection
// must remain idle before the first TCP keepalive
// packet is sent. Once this time is reached,
// tcpKeepaliveInterval option is used instead.
tcpKeepaliveIdle = 60 * time.Second

// tcpKeepaliveInterval specifies the interval
// time between sending TCP keepalive packets.
tcpKeepaliveInterval = 30 * time.Second
```

**Comment by f4nff** [comment]
难怪我改系统参数没啥效果，这个时间其实可以减半，

**Comment by xjasonlyu** [comment]
对啊，所以才有keepalive这个机制。之所以会有原本这么久的timeout，有一部分原因是因为tcp他不知道你到底是进程炸了还是网炸了，如果是因为那会儿丢包率高了导致tcp误以为你是进程炸了不就误杀connection了嘛，所以这么久纯属是为了保守起见。。

**Comment by f4nff** [comment]
```
const (
	// defaultWndSize if set to zero, the default
	// receive window buffer size is used instead.
	defaultWndSize = 0

	// maxConnAttempts specifies the maximum number
	// of in-flight tcp connection attempts.
	maxConnAttempts = 2 << 10

	// tcpKeepaliveIdle specifies the time a connection
	// must remain idle before the first TCP keepalive
	// packet is sent. Once this time is reached,
	// tcpKeepaliveInterval option is used instead.
	tcpKeepaliveIdle = 60 * time.Second

	// tcpKeepaliveInterval specifies the interval
	// time between sending TCP keepalive packets.
	tcpKeepaliveInterval = 30 * time.Second
)
```


能解释下吗，怎么改短一些，

**Comment by f4nff** [comment]
```
	tcpKeepaliveIdle = 30 * time.Second
	tcpKeepaliveInterval = 15 * time.Second
```

改成这样，怎么还需要好久，

**Comment by f4nff** [comment]
```
	// maxConnAttempts specifies the maximum number
	// of in-flight tcp connection attempts.
	maxConnAttempts = 2 << 10
```

这是次数吗？  这个代表多少次？

**Comment by f4nff** [comment]
[https://github.com/xjasonlyu/tun2socks/commit/dba8d77c4b1915a73e65f7081b12f2ef50d391ec](https://github.com/xjasonlyu/tun2socks/commit/dba8d77c4b1915a73e65f7081b12f2ef50d391ec)

看到了这个，我测一下。

**Comment by xjasonlyu** [comment]
https://github.com/xjasonlyu/tun2socks/blob/dba8d77c4b1915a73e65f7081b12f2ef50d391ec/core/stack/tcp.go#L23-L37

把count改小一点就好

**Comment by xjasonlyu** [comment]
@f4nff 你可以提个用配置文件修改一些netstack参数的feature，我以后有空支持一下。

**Comment by f4nff** [comment]
我先编译试试好不好使，

**Comment by f4nff** [comment]
```
const (
	// defaultWndSize if set to zero, the default
	// receive window buffer size is used instead.
	defaultWndSize = 0

	// maxConnAttempts specifies the maximum number
	// of in-flight tcp connection attempts.
	maxConnAttempts = 2 << 10

	// tcpKeepaliveIdle specifies the time a connection
	// must remain idle before the first TCP keepalive
	// packet is sent. Once this time is reached,
	// tcpKeepaliveInterval option is used instead.
	tcpKeepaliveIdle = 30 * time.Second

	// tcpKeepaliveInterval specifies the interval
	// time between sending TCP keepalive packets.
	tcpKeepaliveInterval = 15 * time.Second

	// tcpKeepaliveCount is the maximum number of
	// TCP keep-alive probes to send before giving up
	// and killing the connection if no response is
	// obtained from the other end.
	tcpKeepaliveCount = 2
)
```
<img width="635" alt="image" src="https://user-images.githubusercontent.com/19538878/153742729-4128033b-4017-42f9-878d-dc5e5f14fd64.png">
4分钟了，都没释放。

**Comment by xjasonlyu** [comment]
你现在一般过多久释放？

**Comment by xjasonlyu** [comment]
https://github.com/xjasonlyu/tun2socks/blob/c68dd0771e55a68ef5f777d174345659dfee589b/proxy/util.go#L8-L18

这里有个参数是控制proxy侧的，可能是你忽然关了测试进程，但是proxy侧依然在接收数据，导致没有触发读等待超时，就只能等proxy侧也超时关闭了。

**Comment by f4nff** [comment]
不应该这么判断吧，只要有一方判断断开，就需要主动断开与代理服务器的连接才对，

**Comment by f4nff** [comment]
一方超时，就要断开整个pipe，

**Comment by f4nff** [comment]
客户端这边进程断开了，tun应该主动断开与代理服务器的连接，代理服务器再去主动断开与服务端的连接，

**Comment by xjasonlyu** [comment]
> 不应该这么判断吧，只要有一方判断断开，就需要主动断开与代理服务器的连接才对，

本来就是这样的。就是你可能触发了什么exception。

**Comment by f4nff** [comment]
2.3.2也存在，我直接结束进程，
其他并发程序突然关闭进程应该也存在，非优雅关闭应该都存在，应该是tcpKeepalive这几个参数没生效的原因，

**Comment by f4nff** [comment]
本机好像无法复现，要丢在软路由器里面，用下面的机子并发请求，然后关闭进程，

**Comment by xjasonlyu** [comment]
> 本机好像无法复现，要丢在软路由器里面，用下面的机子并发请求，然后关闭进程，

我就是这么测试的。

**Comment by f4nff** [comment]
会不会跟我用arm r4s有关，

**Comment by xjasonlyu** [comment]
> 会不会跟我用arm r4s有关，

都是Linux，最多就是内核不同，跟CPU架构没关系。

**Comment by f4nff** [comment]
[log.zip](https://github.com/xjasonlyu/tun2socks/files/8056021/log.zip)

这是日志。

**Comment by f4nff** [comment]
[log.zip](https://github.com/xjasonlyu/tun2socks/files/8056039/log.zip)

**Comment by xjasonlyu** [comment]
你下次开-stats :9000参数，然后浏览器去xxx:9000/connections看一下情况。你的日志显示都是马上正常关闭了的，根本用不到keepalive。。

**Comment by xjasonlyu** [comment]
而且你用的socks5 服务端是什么，返回了很多host unreachable 的错误。。

**Comment by f4nff** [comment]
gost

**Comment by xjasonlyu** [comment]
我觉得很有可能是你哪里弄错导致的问题，我又试着复现但依旧不会。

**Comment by f4nff** [comment]
晚会我把连接打印出来看看

**Comment by f4nff** [comment]
[conn1.txt](https://github.com/xjasonlyu/tun2socks/files/8058517/conn1.txt)

这是启动并发关闭之后的连接。
[conn2.txt](https://github.com/xjasonlyu/tun2socks/files/8058551/conn2.txt)

conn2是等了几分钟之后的连接状态。

**Comment by f4nff** [comment]
`{"network":"tcp","sourceIP":"24e5:8100::3c4d:58ca:ac2e:ec74","dialerIP":"127.0.0.1","destinationIP":"2607:f8b0:4007:810::2004","sourcePort":54249,"dialerPort":32060,"destinationPort":443},"upload":741,"download":10341},{"start":"2022-02-14T06:54:52.558742015Z","id":"dfd8f07b-82d8-4a62-bb22-31e00ede229b","metadata":`

可以看到2607:f8b0:4007:810::2004连接这个，关闭并发程序时候，释放比较慢，但是最后也会释放。

**Comment by xjasonlyu** [comment]
> 这是启动并发关闭之后的连接。

启动stress测试然后忽然关闭程序后，获取的连接？

> conn2是等了几分钟之后的连接状态。

这是什么意思，意思是你等了几分钟之后理论上应该要释放但是没释放的连接么。。

**Comment by f4nff** [comment]
这是启动并发关闭之后的连接。

启动stress测试然后忽然关闭程序后，获取的连接？

对的。

conn2的意义不大，意思也会释放，但是释放的速度比较慢，

**Comment by xjasonlyu** [comment]
conn2意义很大，你到底是过了多久才获取的，这上面显示你已经都释放完了，所以没有任何问题。

**Comment by f4nff** [comment]
5分钟左右吧，释放没问题，但是释放时间在哪控制，不确定，你提供那个参数，昨天我调整之后，好像还是5分左右，

**Comment by xjasonlyu** [comment]
> 5分钟左右吧，释放没问题，但是释放时间在哪控制，不确定，你提供那个参数，昨天我调整之后，好像还是5分左右，

你把keepalive时间缩小到1分钟之内，比如count=2，interval=10s，idle=10s，然后你看看是不是还是要5分钟才释放。

你分别截一下，关闭程序1分钟，2分钟，4分钟，5分钟（全部释放完）的connections信息。

**Comment by f4nff** [comment]
```
const (
	// defaultWndSize if set to zero, the default
	// receive window buffer size is used instead.
	defaultWndSize = 0

	// maxConnAttempts specifies the maximum number
	// of in-flight tcp connection attempts.
	maxConnAttempts = 2 << 10

	// tcpKeepaliveIdle specifies the time a connection
	// must remain idle before the first TCP keepalive
	// packet is sent. Once this time is reached,
	// tcpKeepaliveInterval option is used instead.
	tcpKeepaliveIdle = 10 * time.Second

	// tcpKeepaliveInterval specifies the interval
	// time between sending TCP keepalive packets.
	tcpKeepaliveInterval = 10 * time.Second

	// tcpKeepaliveCount is the maximum number of
	// TCP keep-alive probes to send before giving up
	// and killing the connection if no response is
	// obtained from the other end.
	tcpKeepaliveCount = 2
)
```

重新编译之后，
http://10.10.1.1:9000/connections
一直刷新这个页面，到并发连接完全消失，大概用了4分钟。

**Comment by f4nff** [comment]
按道理来说，20秒就应该消失了。

**Comment by f4nff** [comment]
[stress.zip](https://github.com/xjasonlyu/tun2socks/files/8058710/stress.zip)

`win-32.exe -n -1 -c 1000  -m POST https://www.google.com/`

你试试

**Comment by xjasonlyu** [comment]
> 按道理来说，20秒就应该消失了。

理论上40秒左右释放完。

> 分别截一下，关闭程序1分钟，2分钟，4分钟，5分钟（全部释放完）的connections信息。

我需要你每隔一分钟导出一下connections信息，我本地无法复现。

**Comment by f4nff** [comment]
[conn0.txt](https://github.com/xjasonlyu/tun2socks/files/8058756/conn0.txt)
[conn1.txt](https://github.com/xjasonlyu/tun2socks/files/8058757/conn1.txt)
[2.txt](https://github.com/xjasonlyu/tun2socks/files/8058758/2.txt)
[3.txt](https://github.com/xjasonlyu/tun2socks/files/8058759/3.txt)
[4.txt](https://github.com/xjasonlyu/tun2socks/files/8058760/4.txt)

**Comment by xjasonlyu** [comment]
[Archive.zip](https://github.com/xjasonlyu/tun2socks/files/8058987/Archive.zip)

这里面有1，2，3三个版本，你试试哪些存在问题

**Comment by f4nff** [comment]
1-4分09s
2-4分12s
3-4分12s

三个版本，都是差不多的时间，才释放。
