### ISSUE TITLE
[Bug] 'make tun2socks' builds v3 microarchitecture by default

### ISSUE THREAD

**Issue by chromer030** [xjasonlyu/tun2socks#104]
### Verify steps

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

Latest Git

### What OS are you seeing the problem on?

Linux

### Description

Reflected by Go 1.18 , the default behavior for building binaries is v3 microarchitecture . which is not available on wide range of hardware.

```
This program can only be run on AMD64 processors with v3 microarchitecture support.
```

### How to Reproduce

git clone and make tun2socks

**Comment by xjasonlyu** [comment]
It should be run on most "non-older" chips, so I think make v3 as default is ok.

**Comment by chromer030** [comment]
maybe a switch for non v3 architectures ?

**Comment by xjasonlyu** [comment]
> maybe a switch for non v3 architectures ?

I'll see if it's necessary since I believe most chips support AMD64v3 already.
