### ISSUE TITLE
[Bug] No incoming Traffic

### ISSUE THREAD

**Issue by chromer030** [xjasonlyu/tun2socks#105]
### Verify steps

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [x] I have searched on the [issue tracker](……/) for a related issue.

### Version

Latest Git

### What OS are you seeing the problem on?

Linux

### Description

Compiled from latest [commit](https://github.com/xjasonlyu/tun2socks/commit/2892bc20b341409ceaac08c3815cb9f3b2f1e879) , after running there is no incoming traffic ! , tested with both socks4 and socks5 servers.

latest stable release is OK.

It seems that tun2socks doesn't handle traffic.

**Comment by xjasonlyu** [comment]
Hmm, I just pushed the commits, but not tested yet lol. I'll work on it soon.

**Comment by xjasonlyu** [comment]
fixed
