### ISSUE TITLE
[Bug] panic slice bounds out of range 

### ISSUE THREAD

**Issue by avboy1337** [xjasonlyu/tun2socks#110]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

latest personal compile

### What OS are you seeing the problem on?

Windows

### Description

panic: runtime error: slice bounds out of range [:1523] with capacity 1500

goroutine 30 [running]:
github.com/xjasonlyu/tun2socks/v2/core/device/iobased.(*Endpoint).dispatchLoop(0xc00007c7c0, 0x0?)
	github.com/xjasonlyu/tun2socks/v2/core/device/iobased/endpoint.go:97 +0x25f
created by github.com/xjasonlyu/tun2socks/v2/core/device/iobased.(*Endpoint).Attach.func1
	github.com/xjasonlyu/tun2socks/v2/core/device/iobased/endpoint.go:72 +0x98

### CLI or Config

no

### Logs

```shell
no
```

### How to Reproduce

no

**Comment by avboy1337** [comment]
昨晚网络断了，回来看tun2socks退出了，日志是上面的。有情况老哥随时留言。

**Comment by xjasonlyu** [comment]
你是开了-mtu参数，设置到1500了嘛

**Comment by avboy1337** [comment]
"D:\netch-1.9.5-me\Netch\bin\x64\Release\bin\tun2socks.exe" -device tun://netch -proxy socks5://127.0.0.1:2801 -mtu 1500

是的老哥！

**Comment by xjasonlyu** [comment]
这应该是wintun的问题，它读出来的数据超过了mtu的大小。不过建议windows下最好使用默认的mtu大小（1420）

**Comment by avboy1337** [comment]
OK，感谢老哥指示。准备换ubuntu！
