### ISSUE TITLE
wrong wiki

### ISSUE THREAD

**Issue by FH0** [xjasonlyu/tun2socks#111]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

v2.3.2

### What OS are you seeing the problem on?

Linux

### Description

https://github.com/xjasonlyu/tun2socks/wiki/Interface-configuration#windows-1

"static" is not necessary

**Comment by xjasonlyu** [comment]
Can you explain more about this argument?

**Comment by FH0** [comment]
> netsh interface ipv6 add address <interface> static <address/prefixlength>

should be

> netsh interface ipv6 add address <interface> <address/prefixlength>

**Comment by xjasonlyu** [comment]
Saw the manual, it seems that it should be added for manually set ip address.

![manual](https://content.spiceworksstatic.com/service.community/p/how_to_step_attachments/0000120155/59574d89/attached_file/2017-07-01_03_21_31-Administrator__Command_Prompt.png)

**Comment by FH0** [comment]
sorry for wrong comment，the correct version is

`netsh interface ipv6 add address <interface> static <address/prefixlength>`

should be 

`netsh interface ipv6 add address <interface> <address/prefixlength>`
