### ISSUE TITLE
请问这个库和go-tun2socks开源库的区别是什么？[Feature] 

### ISSUE THREAD

**Issue by wustwg** [xjasonlyu/tun2socks#115]
### Description

我看了你们这两个库都用了go， 
https://github.com/eycorsican/go-tun2socks 用的是lwip，
你文档上说你用的是google的ip协议栈，
仅仅是这些区别吗 ？

### Is this feature related to a specific bug?

no

### Do you have a specific solution in mind?

no

**Comment by xjasonlyu** [comment]
一个用了cgo，一个是纯go；性能区别；支持的代理不同等。

**Comment by wustwg** [comment]
> 一个用了cgo，一个是纯go；性能区别；支持的代理不同等。

能详细说说吗？
1. 哪个性能更好？我看了性能测试，这个库的性能更高一些？
2. 支持的代理有何区别？

**Comment by xjasonlyu** [comment]
[go-tun2socks](https://github.com/eycorsican/go-tun2socks)项目作者已经不再维护了，它的内存占用会低一些，但是极限带宽的吞吐量如测试结果所示比较低。

本质就是to-socks的代理，这里区别不大，而且项目不会考虑去加入各种各样的非标准代理协议。

**Comment by wustwg** [comment]
> 

非常感谢，32个赞！！！
