### ISSUE TITLE
[Feature] Why does tun2socks use gvsior

### ISSUE THREAD

**Issue by ssrshz** [xjasonlyu/tun2socks#116]
### Description

I think，it‘s weight that tun2socks just use the TCP/IP from gvsior ，which is a container sandbox and has  a mount of network performance loss in high  load

**Comment by xjasonlyu** [comment]
1. tun2socks needs a user-space network stack to convert layer three packets to TCP/UDP connections
2. we simply and only use the `tcpip` pkg of gVisor which is originally called [netstack](https://github.com/google/netstack)

BTW, topic like this can be discussed in the [Discussions](https://github.com/xjasonlyu/tun2socks/discussions).

**Comment by ssrshz** [comment]
> 1. tun2socks needs a user-space network stack to convert layer three packets to TCP/UDP connections
> 2. we simply and only use the `tcpip` pkg of gVisor which is originally called [netstack](https://github.com/google/netstack)
> 
> BTW, topic like this can be discussed in the [Discussions](https://github.com/xjasonlyu/tun2socks/discussions).

all right!

**Comment by ssrshz** [comment]
closed
