### ISSUE TITLE
[Bug] read more than actual length

### ISSUE THREAD

**Issue by ssrshz** [xjasonlyu/tun2socks#118]
https://github.com/xjasonlyu/tun2socks/blob/3926f866138b645948ad69ccfa03d97786df3fa8/core/device/iobased/endpoint.go#L113

according to the context,the data‘s max actual length is n,but here is [offset+n]：
n, err := e.rw.Read(data)

**Comment by xjasonlyu** [comment]
The data slice's total length is offset+mtu

https://github.com/xjasonlyu/tun2socks/blob/3926f866138b645948ad69ccfa03d97786df3fa8/core/device/iobased/endpoint.go#L97

then we read n bytes from Read. also, len(data[offset : offset+n]) == n

**Comment by ssrshz** [comment]
> The data slice's total length is offset+mtu
> 
> https://github.com/xjasonlyu/tun2socks/blob/3926f866138b645948ad69ccfa03d97786df3fa8/core/device/iobased/endpoint.go#L97
> 
> then we read n bytes from Read. also, len(data[offset : offset+n]) == n

Oh,but i think the n bytes from Read starts with the “offset” bytes,and data[offset : offset+n] exceeds the length of n.
Maybe I understand wrong？

**Comment by xjasonlyu** [comment]
> and data[offset : offset+n] exceeds the length of n.

No, it doesn't.

Read returns total length it read, regardless of offset. it overwrites offset bytes first.

**Comment by ssrshz** [comment]
> > and data[offset : offset+n] exceeds the length of n.
> 
> No, it doesn't.
> 
> Read returns total length it read, regardless of offset. it overwrites offset bytes first.

er,i see.tks @xjasonlyu 
I'm learning tun2socks recently,this is a great project

**Comment by ssrshz** [comment]
When i debug here, i see all:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/19809226/163333340-1af6a384-11b2-477d-9b28-f07fec42db81.png">



> > > and data[offset : offset+n] exceeds the length of n.
> > 
> > 
> > No, it doesn't.
> > Read returns total length it read, regardless of offset. it overwrites offset bytes first.
> 
> er,i see.tks @xjasonlyu I'm learning tun2socks recently,this is a great project

**Comment by xjasonlyu** [comment]
That's 4 bytes TUN PI header (offset).
