### ISSUE TITLE
编译报错,求大佬指点一番

### ISSUE THREAD

**Issue by wzcheng97** [xjasonlyu/tun2socks#12]
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: 找不到 -lpthread
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: 找不到 -lc
collect2: error: ld returned 1 exit status

**Comment by xjasonlyu** [comment]
啊这。。你这信息有点少，缺什么你装什么就行了呗。。
