### ISSUE TITLE
-interface option doesn't work when socks5 address is 127.0.0.1:1080

### ISSUE THREAD

**Issue by garymaxallen** [xjasonlyu/tun2socks#122]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

lastest

### What OS are you seeing the problem on?

Linux, macOS

### Description

I use the example here, both Linux and macOS, https://github.com/xjasonlyu/tun2socks/wiki/Examples

I use a local socks5 address
![image](https://user-images.githubusercontent.com/10022333/166088606-24c74cad-6fbb-4b84-a472-28fff1d93a9c.png)
and can't ping www.google.com
![image](https://user-images.githubusercontent.com/10022333/166088628-50478b7b-0e6c-4808-bf04-57398605ad0d.png)
ping 8.8.8.8 
![image](https://user-images.githubusercontent.com/10022333/166088648-5b6697e4-bf00-4483-90bd-ffc07e0b3874.png)
my route
![image](https://user-images.githubusercontent.com/10022333/166088652-34f3adb4-a956-455d-b5a7-d095b24b3813.png)

Same thing happens on macOS too.
If you use a remote socks address, it works, but using local socks address, no.

**Comment by xjasonlyu** [comment]
Hi,

If using `127.0.0.1` as proxy server host, you don’t need to bind the interface. Just make sure that your local proxy server won’t get into route looping.

**Comment by garymaxallen** [comment]
thanks, problem solved.

**Comment by Oleg-you** [comment]
> thanks, problem solved.
Tell us how you decided to solve the problem
