### ISSUE TITLE
[Bug] linux create tun: operation not permitted

### ISSUE THREAD

**Issue by llllrg** [xjasonlyu/tun2socks#125]
### Verify steps

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [x] I have searched on the [issue tracker](……/) for a related issue.

### Version

Latest

### What OS are you seeing the problem on?

Linux

### Description

There is no permission to start it, I need to start it without root permission

### Logs

```shell
create tun: operation not permitted
```

**Comment by chromer030** [comment]
Linux operating system doesn't permit you to create tun/tap interfaces without root permission.
