### ISSUE TITLE
Docker multiple containers question

### ISSUE THREAD

**Issue by AvgAwsmDude** [xjasonlyu/tun2socks#128]
Can i run multiple docker container and also run tun2socks docker container and config each of the other containers to a different socks5 proxy that i provide?

**Comment by xjasonlyu** [comment]
I think it should work if you configured properly.

**Comment by chromer030** [comment]
You need to create tun on each container which is explained here how to : https://stackoverflow.com/questions/59451531/how-to-create-tun-interface-inside-docker-container-image
and use tun2socks.

**Comment by AvgAwsmDude** [comment]
@chromer030  why isnt it possible with redsocks?
like i force each containers ip:port to redsocks where i wouldve mapped it to use proxy?

**Comment by AvgAwsmDude** [comment]
@chromer030 im asking this because i found it easy to setup redsocks+iptables but i have no idea how to use tun2socks

**Comment by AvgAwsmDude** [comment]
https://stackoverflow.com/questions/72198113/running-docker-containers-each-with-socsk5-proxy this is what im trying to achieve

**Comment by AvgAwsmDude** [comment]
> I think it should work if you configured properly.

but i want to use just one tun container not one for each other container im trying to proxy

**Comment by AvgAwsmDude** [comment]
damn, it all looks so complicated :'( , tell me , 

```

iptables -t nat -A REDSOCKS -p tcp --dport 80 -j REDIRECT --to-ports 12345
iptables -t nat -A REDSOCKS -p tcp --dport 443 -j REDIRECT --to-ports 12345
iptables -t nat -A REDSOCKS -p tcp --dport 11371 -j REDIRECT --to-ports 12345
```

when i do this , my app runs using the proxy, now if i want to use many instances of my app , how will i get my container ip and port or dport , so that i can map it all right? and provide the right config in redsocks.conf


```

base {

	log_debug = off;


	log_info = on;

	log = "syslog:daemon";


	daemon = on;

	user = redsocks;
	group = redsocks;



	redirector = iptables;
}

redsocks {

	local_ip = 127.0.0.1;
	local_port = 12345;


	ip = proxy-ip;
	port = port;



	type = socks5;

	 login = "user";
	 password = "pass";
}

```

**Comment by xjasonlyu** [comment]
what’s that… don’t make it complicated, iptables is not needed at all in your case.

**Comment by AvgAwsmDude** [comment]
> what’s that… don’t make it complicated, iptables is not needed at all in your case.

Alright , yo redirect  the connections of the containers I need to figure out what ip:port the container is running on , how do I do that?
