### ISSUE TITLE
ld: library not found for -lcrt0.o

### ISSUE THREAD

**Issue by fbion** [xjasonlyu/tun2socks#13]
mac os

GOBUILD=go build -trimpath -ldflags '-s -w  -extldflags "-static" -X "github.com/xjasonlyu/tun2socks/constant.Version=$(VERSION)"'

去掉 Makefile 中的  -extldflags "-static" 就好了?

GOBUILD=go build -trimpath -ldflags '-s -w   -X "github.com/xjasonlyu/tun2socks/constant.Version=$(VERSION)"'

**Comment by xjasonlyu** [comment]
好像是的，基本都在Linux下编译测试的，MacOS下后来没测试编译过。
