### ISSUE TITLE
[Bug] cannot unmarshal !!str "50" into time.Duration

### ISSUE THREAD

**Issue by zhaodice** [xjasonlyu/tun2socks#130]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.4.1

### What OS are you seeing the problem on?

Windows, Linux

### Description

https://github.com/xjasonlyu/tun2socks/commit/31e19a069071886f5377050457079d37309b3711
How can I describe time.Duration data by config file or a parameter?

### How to Reproduce

 when I use -udp-timeout 60 or in yaml config file, got ERROR.

**Comment by xjasonlyu** [comment]
Try: `60s`, `1h30m`, etc.

**Comment by zhaodice** [comment]
> 

Thanks, but could you update this wiki with new format : https://github.com/xjasonlyu/tun2socks/wiki/Configuration

**Comment by xjasonlyu** [comment]
Updated, thanks.
