### ISSUE TITLE
win7环境下创建多个tun,有没有办法解决，但是win10 貌似没有，求解决方案？

### ISSUE THREAD

**Issue by alsojin0806** [xjasonlyu/tun2socks#134]
RT

.

**Comment by m2acgi** [comment]
同问。已经是第 17 个了. 
![2022-05-24_15-17-13_explorer](https://user-images.githubusercontent.com/34497122/169971844-fcbf8a22-ea05-4397-a794-51d016f6cb30.png)

**Comment by xjasonlyu** [comment]
是用什么参数创建的？

**Comment by m2acgi** [comment]
`tun2socks -device tun://tun0 -loglevel debug -proxy ss://method:password@server_host:port`

**Comment by xjasonlyu** [comment]
另一个用tun://tun1这样的不行吗

**Comment by alsojin0806** [comment]
我尝试手动卸载能解决，这样似乎不理想，有没有比较合理的方案？

**Comment by m2acgi** [comment]
我是同时只运行一个，关闭再运行，tun 序号就会加 1

其实对使用没什么实质影响

**Comment by alsojin0806** [comment]
@xjasonlyu 大佬 有卸载wintun的方案没？

**Comment by rurirei** [comment]
seems that's a feature Windows brings here:
>> Why does my Network status says Network 2?
Network 2 is just the name Windows gives to your network adapters, and sometimes after re-installing them it tends to name them Network 2, Network 3 etc.
