### ISSUE TITLE
[Feature] Reverse functionality: socks2tun

### ISSUE THREAD

**Issue by ValdikSS** [xjasonlyu/tun2socks#148]
### Description

When you have a proxy and want to convert it to the interface and use it system-wide, you use software like tun2socks. There are several programs like tun2socks available because that's the only way to use proxy on Android, where only TUN (VPN) interface is available for handling.

However, when you have a VPN and want to expose it as a proxy, there's not much solutions out there. There's [openconnect](https://gitlab.com/openconnect/openconnect) which supports redirection of TUN traffic to the file descriptor to be used with [ocproxy](https://github.com/cernekee/ocproxy) or [tunsocks](https://github.com/russdill/tunsocks/issues), there's [wg-http-proxy](https://github.com/shimberger/wg-http-proxy) and [wghttp](https://github.com/zhsj/wghttp) for WireGuard protocol.
The first does not support Windows. Neither support OpenVPN.

There's a [patch for OpenVPN](https://sourceforge.net/p/openvpn/mailman/openvpn-devel/thread/1397366216-657-1-git-send-email-cernekee%40gmail.com/) to pass TUN traffic over the file descriptor, not to a real TUN device. In fact, this is an adaptation of OpenConnect's `--script` option and it is compatible with ocproxy and tunsocks. But both ocproxy and tunsocks does not support Windows and are based on a lightweight lwIP TCP/IP stack designed for microcontrollers, so it's pretty slow and suboptimal.
The patch is outdated, but [I ported it](https://github.com/ValdikSS/openvpn-tunpipe) to the latest OpenVPN and want to propose it in the main repo for the inclusion.

>There are many use-cases for exposing VPN as a proxy:
> - Routing traffic from different applications through different VPNs.
> - Connecting to multiple VPNs (clients, sites, ...) that have overlapping IP ranges.
> - Connecting to multiple VPNs that each advertise their own default route and/or DNS settings.
> - Situations in which direct access to the VPN from all processes/UIDs is not necessarily wanted, impairs performance, or presents an unacceptable risk of intrusion or data leakage.
> - Multiuser systems or container-based VPSes.
> - Other situations in which the openvpn user or program is not trusted to reconfigure a tun/tap device.

### Do you have a specific solution in mind?

May I ask you to implement socks2tun functionality in your software, i.e. read TUN data from the fd, pass it inside gVisor's TCP/IP stack and expose it as a SOCKS/HTTP proxy port? Your software is fast and cross-platform, this would be very handy, especially for Windows users where configuring multiple VPNs or VPN over proxy like Tor, where the destination IP address is dynamic, is borderline impossible.

This could be also adapted to other software and protocols, for example, I'm planning to make a plugin for strongSwan to support userspace IPsec IKEv2 proxy as well.

**Comment by ValdikSS** [comment]
There was similar proposal in #26, but without technical implementation details, that's why I opened a new one.

**Comment by ValdikSS** [comment]
@xjasonlyu, what do you think about this proposal? Is it hard to implement, or you're just not interested in this functionality in tun2socks project?

**Comment by xjasonlyu** [comment]
Hi, sorry for the late reply. I haven't had enough time recently to make new features for this project, and I also think your proposal deserves a new `socks2tun` project rather than adding it as a feature.

**Comment by paolosezart** [comment]
I was also interested in the reverse functionality of socks2tun. And I would like to know if there are any plans to implement such a function or project?

**Comment by mymirai-nikki** [comment]
does this tun2socks project currently support L2TP + IPSec? I'm not fully understand how it works, I configure L2TP server to get routed to tun2socks to connect to gost socks5 proxy, but I often get this `'Timeout was reached'` messages'

EDIT: apparently this is [not supported yet](https://deepwiki.com/search/does-this-tun2socks-project-cu_fc990530-4cc2-4bd6-a5c6-159891a4a19f?mode=deep)

**Comment by handpickencounter** [comment]
The proposed feature seems to me to be a "holding it wrong" type of problem.


> 
>     There are many use-cases for exposing VPN as a proxy:
> 
>         Routing traffic from different applications through different VPNs.
>         Connecting to multiple VPNs (clients, sites, ...) that have overlapping IP ranges.
>         Connecting to multiple VPNs that each advertise their own default route and/or DNS settings.
>         Situations in which direct access to the VPN from all processes/UIDs is not necessarily wanted, impairs performance, or presents an unacceptable risk of intrusion or data leakage.
>         Multiuser systems or container-based VPSes.
>         Other situations in which the openvpn user or program is not trusted to reconfigure a tun/tap device.
> 

Every single one of those use-cases is solved with network namespaces.

ex. https://www.wireguard.com/netns/ (applies to non wireguard too)

You can also spawn something like passt in each of those namespaces and now you have a high performance "proxy" living as a UDS in your file system. some sandboxing tools can utilize passt. ex. https://github.com/AsahiLinux/muvm

You can even run a socks5 server in each of those namespaces and smuggle it out if you really want to.


There is also https://github.com/containers/gvisor-tap-vsock
