### ISSUE TITLE
[Bug] Creating interface error in Windows 7

### ISSUE THREAD

**Issue by sunxu888** [xjasonlyu/tun2socks#157]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.4.1

### Description

win7下，已经安装了KB2533623X64 补丁，会不会是虚拟机原因

### Logs

```shell
C:\Users\Administrator\Desktop\tun2socks>tun2socks -device "ShanYou_Tun_Connection" -proxy socks5://127.0.0.1:21180
2022/08/11 21:23:19 Using existing driver 0.14
2022/08/11 21:23:19 Creating adapter
2022/08/11 21:23:19 Spawning native process to create instance
2022/08/11 21:23:43 Failed to setup adapter (problem code: 0x34): 由于硬件错误，
显示设备需要重新初始化。 (Code 0x0000048C)
2022/08/11 21:23:43 Spawning native process to remove instance
time="2022-08-11T21:23:44+08:00" level=fatal msg="[ENGINE] failed to start: crea
te tun: Error creating interface: The indicated device requires reinitialization
 due to hardware errors."
```

**Comment by tcc-123** [comment]
I have encountered the same problem as you, which was reported as an error on the Win7 and x64 virtual machines.
After Google, I found that the patch was missing, and I have resolved it. 
We need this patch: kb4474419

**Comment by tcc-123** [comment]
download address
https://catalog.update.microsoft.com/search.aspx?q=kb4474419
