### ISSUE TITLE
[Feature] Support Socks 6 Proxy

### ISSUE THREAD

**Issue by wizd** [xjasonlyu/tun2socks#159]
### Description

For tcp connection with an optional header such as MPTCP [link](https://www.rfc-editor.org/rfc/rfc6824.html), Socks6 was introduced. [link](https://datatracker.ietf.org/meeting/99/materials/slides-99-intarea-socks6-00). If tun2socks can handle tcp optional header, that will be great!

**Comment by xjasonlyu** [comment]
But I haven’t seen any popular socks6 server implementation yet.

**Comment by wizd** [comment]
You are right. I wonder if mptcp goes more popular there will be a lot of needs. A lot of network management protocols use option header also. If this [fork](https://github.com/45G/shadowsocks-libev) get merged there will be a popular socks6 proxy.

**Comment by chromer030** [comment]
Aside the server side , is there any client to support socks 6 yet ?
