### ISSUE TITLE
[Bug] udp not working

### ISSUE THREAD

**Issue by snltty** [xjasonlyu/tun2socks#163]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.4.1

### What OS are you seeing the problem on?

Windows

### Description

tun2socks-windows.exe  -device p2p-tunnel -proxy socks5://127.0.0.1:5412 -loglevel silent

in the socks5, step command,
tcp is ok ,  udp got  0.0.0.0:0  target  ipendpoint
![1](https://user-images.githubusercontent.com/10977033/190051596-6a9a55c5-9576-475a-9ba1-bc4648575214.png)

**Comment by xjasonlyu** [comment]
> The UDP ASSOCIATE request is used to establish an association within
   the UDP relay process to handle UDP datagrams.  The DST.ADDR and
   DST.PORT fields contain the address and port that the client expects
   to use to send UDP datagrams on for the association.  The server MAY
   use this information to limit access to the association.  **If the
   client is not in possesion of the information at the time of the UDP
   ASSOCIATE, the client MUST use a port number and address of all
   zeros.**

This might be your socks server side’s problem. In socks5, client can use unspecific ip (in this case, `0.0.0.0`) as target ip and zero port number as target port, but obviously your socks server doesn’t support this feature. So you may should contact your server provider about this issue.

**Comment by snltty** [comment]
Thank you~
I'll try

**Comment by snltty** [comment]
command 0x03  is, UDP ASSOCIATE
![2](https://user-images.githubusercontent.com/10977033/190053789-b0309884-3a31-4ff9-8a46-5337ceafea05.png)

**Comment by xjasonlyu** [comment]
yep

**Comment by snltty** [comment]
I Dont Understand
why got  0.0.0.0:0
