### ISSUE TITLE
[Bug] UDP response from the proxy server isn't processed properly

### ISSUE THREAD

**Issue by Cherser-s** [xjasonlyu/tun2socks#164]
### Verify steps

- [x] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.4.1

### What OS are you seeing the problem on?

Linux

### Description

UDP relay processes address incorrectly. When testing connection to Google DNS, the client generates the packet with source port 40689 and then relay uses src port 43123 to send the packet to the proxy server. Method `ReadFrom` within `proxy/socks5.go` returns the `192.168.100.72:40689` instead of `8.8.8.8:53`. I used Microtik built-in socks5 proxy server to test the connection.

The DNS response did go through when I removed this branching snippet: https://github.com/xjasonlyu/tun2socks/blob/main/tunnel/udp.go#L124

### Logs

```shell
time="2022-09-14T17:06:54+03:00" level=info msg="[UDP] 192.168.100.72:43123 <-> 8.8.8.8:53"
time="2022-09-14T17:06:54+03:00" level=warning msg="[UDP] symmetric NAT 192.168.100.72:43123->8.8.8.8:53: drop packet from 192.168.100.72:40689"
```

**Comment by xjasonlyu** [comment]
It’s expected in symmetric NAT, but I don’t understand why it received local udp packet instead of 8.8.8.8. 

Did you try other proxy servers? Mine works fine with querying DNS.

**Comment by Cherser-s** [comment]
It doesn't receive local UDP packet, it does receive it from 8.8.8.8 (through proxy)
The problem is that the IP address inside the encapsulated socks packet is the destination address and not the source one. That happens with any UDP use-case.

**Comment by Cherser-s** [comment]
Also doesn't RFC 1928 state that the DST address field in the reply from the proxy server should be the real destination which the relay should send the packet to?

**Comment by xjasonlyu** [comment]
> Also doesn't RFC 1928 state that the DST address field in the reply from the proxy server should be the real destination which the relay should send the packet to?

Yes and that’s how it implemented.

**Comment by Cherser-s** [comment]
>  Yes and that’s how it implemented.

It isn't?

Why the `from` variable [here](https://github.com/xjasonlyu/tun2socks/blob/1ecd587857d10423865205b9f658fd94e5af184b/tunnel/udp.go#L124) (which in my case was 192.168.100.72:40689) is compared with dst (which in my case is 8.8.8.8:53) instead of src? The `from` variable in here is actually the destination address from the proxy server's perspective and not from the client's (it should be 8.8.8.8).

**Comment by xjasonlyu** [comment]
> Why the from variable [here](https://github.com/xjasonlyu/tun2socks/blob/1ecd587857d10423865205b9f658fd94e5af184b/tunnel/udp.go#L124) (which in my case was 192.168.100.72:40689) is compared with dst (which in my case is 8.8.8.8:53)?

To make sure that the address is NAT’s destination address. 

And I think the code is probably ok because I have tested it many times and didn’t encounter these kind of issues.

**Comment by Cherser-s** [comment]
Shouldn't pc.src and pc.dst be associated with client's source and destination address in this case instead of client's dst address and the proxy server dst address?
