### ISSUE TITLE
[Bug]  can't relay UDP under v2ray socks5

### ISSUE THREAD

**Issue by Taylor-lagrange** [xjasonlyu/tun2socks#165]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.4.1

### What OS are you seeing the problem on?

Linux

### Description

I use v2ray set up a sock5 proxy in addr 127.0.0.1:1080, but I find UDP can't be relay correctly.

When I check the code and capture net package, I find tun2socks send UDP ASSOCIATE request by ip 127.0.0.1,  but later the udp pakage be relayed  by ip 10.28.253.3, which is the ip of my interface wlp0s20f3. So the v2ray just drop this udp pakage silently.

![image](https://user-images.githubusercontent.com/46434815/190302939-077faff7-3a38-428d-86c0-8e322518bd74.png)

![image](https://user-images.githubusercontent.com/46434815/190303062-b61373e0-625a-4ea9-a2e4-d5582a2aaa0d.png)

when I change the code , force tun2socks use 127.0.0.1 to send upd relay pakage, problem fixed. But I'm not sure it's a bug or just I use tun2socks wrongly.

### CLI or Config

tun2socks --loglevel debug --udp-timeout 20 --proxy socks5://127.0.0.1:1080 -interface wlp0s20f3 --device tun://tun0

**Comment by xjasonlyu** [comment]
You shouldn’t bind to an interface while using 127.0.0.1 as target proxy ip. Simply remove the interface parameter may do the trick.
