### ISSUE TITLE
[Bug] Can't send ipv6 request through curl --interface

### ISSUE THREAD

**Issue by tiannian** [xjasonlyu/tun2socks#178]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.4.1

### What OS are you seeing the problem on?

Linux

### Description

我使用curl --interface tun0测试ipv6发现无法访问，日志开启了debug也没有任何输出。但是访问一个ipv4地址是没有问题的。包括ping指令也是这样的，ipv6也是无法访问，ipv4地址完全没问题。DNS能够正常解析ipv6。

### CLI or Config

tun2socks -loglevel debug -device tun://tun0 -proxy socks5://[::1]:7891

**Comment by xjasonlyu** [comment]
如果无法ping通ipv6的话，说明是tun接口的v6地址未正确配置。

**Comment by tiannian** [comment]
搞定了，感谢。
