### ISSUE TITLE
[Feature] cant connet

### ISSUE THREAD

**Issue by vahidx4r4x** [xjasonlyu/tun2socks#185]
### Description

Hi, 
Thanks for your great work

I have problem with tun2socks and Shadowsocks
Im using `shadowsocks + cloak` to connect to internet and Its annoying that Shadowsocks app cant achive the whole system tunneling, some of my apps will connect directly and no other apps like `Proxifier` could help.
I saw your `tun2socks` app and tried it but I cant figure it out! I dont know how to tell `tun2socks` to creat the tap adapter to achive the whole system tunneling and pull the internet traffic from Shadowsocks.

shadowsocks normaly creats a local socks proxy and port (`localhost on port 1080`) and set it on windows proxy settings
I dont know how to tell `tun2socks` that it should listen to `localhost:1080` and route the traffic to my wi-fi adapter?

Cant you help me?

**Comment by xjasonlyu** [comment]
> I dont know how to tell tun2socks that it should listen to localhost:1080 and route the traffic to my wi-fi adapter?

Didn't get it. tun2socks simply proxify your traffic to your proxy. it doesn't listen to address or route to adapter.

**Comment by vahidx4r4x** [comment]
I was thinking what tun2socks do is forwarding the proxy traffic to the tap/tun adapter so you can proxify whole system.

So how can I tell tun2socks to connect to my Shadowsocks + cloak server?
