### ISSUE TITLE
Any plan to add freebsd ?

### ISSUE THREAD

**Issue by chromer030** [xjasonlyu/tun2socks#19]

**Comment by xjasonlyu** [comment]
Maybe later,, but I'm not sure if it would work like a charm in Linux.

**Comment by xjasonlyu** [comment]
@chromer030 added bsd experimental support, it might be unstable or buggy, please see new commits.

**Comment by chromer030** [comment]
@xjasonlyu Thank you man , i will test and report.
Thanks again for this great tool and your efforts.
