### ISSUE TITLE
[Feature] Option to Enable DNS fallback over TCP

### ISSUE THREAD

**Issue by xtianxian** [xjasonlyu/tun2socks#191]
### Description

When socks proxy does not support UDP, let users have the option for dns fallback over TCP

### Do you have a specific solution in mind?

This feature is available in this go tun2sokcs implementation using the flag --dnsfallback=true
https://github.com/eycorsican/go-tun2socks

**Comment by xjasonlyu** [comment]
Hmm, I got your point. However, I believe this need could be solved by using external DNS tools (DNS-TCP or DoH), making this project more concise.
