### ISSUE TITLE
是否支持ios/mac？[Feature] 

### ISSUE THREAD

**Issue by ding2chen** [xjasonlyu/tun2socks#193]
### Description

是否支持ios/mac？[Feature]

**Comment by xjasonlyu** [comment]
Darwin/macOS is supported natively, while iOS is not officially supported but can be built on your own.

**Comment by ding2chen** [comment]
thanks

**Comment by dhp5** [comment]
> Darwin/macOS 原生支持，iOS 暂未得到官方支持，但可以自行构建。

I can't use gomobile to package into the xcframework required for ios, what should I do?
