### ISSUE TITLE
[Bug] tun2socks does nothing

### ISSUE THREAD

**Issue by izulwahidin** [xjasonlyu/tun2socks#198]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

tun2socks-2.4.1 linux/amd64, go1.18, 77e8ad4

### What OS are you seeing the problem on?

Linux

### Description

so right now i have local socks5 proxy on port 7890 running.

i tried to run this cli
`sudo tun2socks -device tun0 -proxy socks5://127.0.0.1:7890 -interface wlp5s0 -loglevel "debug"`
but its not working for some reason on my end.

the log only show **2 line**

i can confirm that the socks5 is **working**

FYI: i dont know this parameter comes from "**-device tun0**" so i just write **tun0** since i dont kow

### CLI or Config

sudo tun2socks --device tun0 -proxy socks5://127.0.0.1:7890 -interface wlp5s0 -loglevel "debug"

### Logs

```shell
INFO[0000] [DIALER] bind to interface: wlp5s0           
INFO[0000] [STACK] tun://tun0 <-> socks5://127.0.0.1:7890
```

**Comment by chromer030** [comment]
https://github.com/xjasonlyu/tun2socks/wiki/Route-Configuration

**Comment by Saeed-Pooyanfar** [comment]
https://medium.com/@SaeedPooyanfar/use-socks-proxy-as-vpn-in-linux-d31b1cce44e0
