### ISSUE TITLE
[Bug] High CPU usage

### ISSUE THREAD

**Issue by chromer030** [xjasonlyu/tun2socks#199]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

latest git

### What OS are you seeing the problem on?

Linux

### Description

High cpu usage and new error on log :

![Screenshot_20221217_201424](https://user-images.githubusercontent.com/13361552/208252326-e0674e83-aabd-4873-b72c-4763a2f72033.jpg)

### Logs

```shell
W1217 20:15:42.053644   19519 gonet.go:457] ep.GetRemoteAddress() failed: endpoint not connected
W1217 20:15:54.619820   19519 gonet.go:457] ep.GetRemoteAddress() failed: endpoint not connected
W1217 20:16:14.710499   19519 gonet.go:457] ep.GetRemoteAddress() failed: endpoint not connected
W1217 20:16:14.932769   19519 gonet.go:457] ep.GetRemoteAddress() failed: endpoint not connected
W1217 20:16:21.858031   19519 gonet.go:457] ep.GetRemoteAddress() failed: endpoint not connected
```

**Comment by xjasonlyu** [comment]
Weird, it must be a problem from the latest gVisor's commits.

**Comment by chromer030** [comment]
Fixed in 30608f4925b7ce83bd38104b0612db6c77f1611e , Thank you !

**Comment by xjasonlyu** [comment]
That's not how it works. The lower UDP speed is due to the missing of congestion control algorithm.

**Comment by xjasonlyu** [comment]
Could be.

**Comment by xjasonlyu** [comment]
It depends on your specific circumstance.
