### ISSUE TITLE
[Feature] TFO (TCP FastOpen)

### ISSUE THREAD

**Issue by GektorUA** [xjasonlyu/tun2socks#206]
### Description

Is tun2socks supports TFO (TCP FastOpen)?

**Comment by xjasonlyu** [comment]
Hmm, I think it's not quite necessary though.

**Comment by chromer030** [comment]
Is there any significant performance/speed difference with and without TFO ?

**Comment by xjasonlyu** [comment]
No, TFO only speeds up TCP establishment a bit. But in most cases, we only use tun2socks locally, which makes enable it pointless.
