### ISSUE TITLE
Problem with dns

### ISSUE THREAD

**Issue by hdid** [xjasonlyu/tun2socks#21]
Hi
I'm using go-tun2socks and my attached router can resolve dns requests through that. Commands that i'm using:
go-tun2socks -proxyServer "ip:1080" -tunName tun2
ip addr add dev tun2 10.255.0.2
*ip link set dev tun2 up
ip route add socks-server-ip via default-gw-ip
ip route add 0/1 dev tun2
ip route add 128/1 dev tun2
Both socks server and client support udp and everything works but with a bit latency.
Yesterday, i switched to your project with this commands:
tun2socks-linux-amd64 --device tun://tun2 --proxy socks5://ip:1080 --interface wlan0   # my local machine gets internet via wlan0
ip addr add dev tun2 198.18.0.1/15
And other cmds are like upper *
But then could not use any dns request to public resolvers like 8.8.8.8 or 9.9.9.9
Do i need to do any further action? With fake dns function (--dns dns://:53) i can browse internet but there is issue with torrent download!
Thank you

**Comment by xjasonlyu** [comment]
Could you provide extra running logs and your routing table?

DNS over proxy is supported by this project, and policy routing is recommended in Linux.

**Comment by hdid** [comment]
Removing the "--interface wlan0" option resolved the issue.
