### ISSUE TITLE
[Feature] Reverse Socks5 proxy

### ISSUE THREAD

**Issue by SkullFace141** [xjasonlyu/tun2socks#214]
### Description

Can you implement reverse proxy so that a a server can be proxified and have open ports for incoming connections on the proxy?

### Is this feature related to a specific bug?

No

### Do you have a specific solution in mind?

No

**Comment by xjasonlyu** [comment]
Didn't get it. What's the point of it?

**Comment by SkullFace141** [comment]
Hosting services like websites behind socks5
