### ISSUE TITLE
how can i get the interface which i created's file path

### ISSUE THREAD

**Issue by johnnyhansen-away** [xjasonlyu/tun2socks#227]
### Description

hello, i want to get the interface 's file path, but i didn't.
please help me how to get this. such as i created -device utun123
where is the interface's file path to utun123,
the tun/tap 's interface always at /dev/tunXX, but where is utunXXX, thank you!

**Comment by xjasonlyu** [comment]
tun in macOS seems to work a bit differently
- https://stackoverflow.com/questions/13035220/interfacing-with-tun-tap-for-mac-osx-lion-using-python

**Comment by johnnyhansen-away** [comment]
i don't know what's different between tun and utun,  tun2socks only support utun[0-9]. 
but i want to get the interface's file path. can i?

**Comment by xjasonlyu** [comment]
Naming like `utun[0-9]+` is required by macOS, but I'm not sure about the file path.

**Comment by johnnyhansen-away** [comment]
OK! thank you
