### ISSUE TITLE
[Bug] [UDP] dial 8.8.8.8:53: client handshake: EOF 

### ISSUE THREAD

**Issue by qaiwiz** [xjasonlyu/tun2socks#230]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

tun2socks-2.4.1 darwin/amd64, go1.20.1, 6cfc253

### What OS are you seeing the problem on?

macOS

### Description

I am trying to setup tun2socks on my macos laptop. I already have a server running at xx.xx.xx.xx

ssh -D 1080 user@xx.xx.xx.xx

then I run tun2socks:
sudo tun2socks -device utun123 -proxy socks5://127.0.0.1:1080 -interface en0
sudo ifconfig utun123 198.18.0.1 198.18.0.1 up

followed by 
sudo route add -net 1.0.0.0/8 198.18.0.1
sudo route add -net 2.0.0.0/7 198.18.0.1
sudo route add -net 4.0.0.0/6 198.18.0.1
sudo route add -net 8.0.0.0/5 198.18.0.1
sudo route add -net 16.0.0.0/4 198.18.0.1
sudo route add -net 32.0.0.0/3 198.18.0.1
sudo route add -net 64.0.0.0/2 198.18.0.1
sudo route add -net 128.0.0.0/1 198.18.0.1
sudo route add -net 198.18.0.0/15 198.18.0.1

Then I get continuous UDP warning:
[UDP] dial 8.8.8.8:53: client handshake: EOF 

Note 1: on the server I have already used ufw to allow port 53/tcp and 53/udp. 
Note 2: I have already running stunnel on the server and client too. when I try the above tun2socks with stunnel, I get this error:
dial xx.xx.xx.xx:port: read tcp 127.0.0.1:60542->127.0.0.1:1080: read: connection reset by peer 
where xx.xx.xx.xx:port are specified in the stunnel config. I should mention that I have no problem using stunnel with SSH -D for socks proxy just to ensure that stunnel config and cert is working fine. 

Is there anything I can do on the server or client to fix the problem with stunnel or just regular port forwarding?

...
WARN[0082] [UDP] dial 8.8.8.8:53: client handshake: EOF 
WARN[0083] [UDP] dial 8.8.8.8:53: client handshake: EOF 
WARN[0085] [UDP] dial 8.8.4.4:53: client handshake: EOF 
WARN[0085] [UDP] dial 8.8.4.4:53: client handshake: EOF 
WARN[0085] [UDP] dial 8.8.4.4:53: client handshake: EOF 
WARN[0085] [UDP] dial 8.8.4.4:53: client handshake: EOF 
WARN[0085] [UDP] dial 8.8.4.4:53: client handshake: EOF 
...

_No response_

**Comment by xjasonlyu** [comment]
If you’re using SSH as the proxy server, then you should know that it doesn’t support UDP, which causes this error.

**Comment by qaiwiz** [comment]
uh thanks. Just a couple of questions/comment:
1) I read that socks5 support udp in addition to tcp! I used to be able to answer my voice call using ssh D+stunnel. 
2) napsternetv (ssh direct) somehow manage to transfer udp (I guess using udpgw) just with socks5 (I am not sure how it is done). 
3) Do you have any idea how to combine tcp/udp over ssh D+stunnel+tun2socks?
4) What is the most organic communication proxy that can be combined with tun2socks? V2ray, OpenVPN, Wireguard, etc can be detected and throttled.

**Comment by xjasonlyu** [comment]
1. right, but not all socks5 servers have UDP supported.
2. no idea, I personally do not recommend to use SSH as a long-time proxy server.
3. v2ray, proxy servers only.

**Comment by xjasonlyu** [comment]
Sorry for the inconvenience

1. v2ray has English ver doc: https://www.v2fly.org/en_US/v5/config/overview.html
2. Try the `trojan` protocol, it should be a good proxy type in areas with network censorship

**Comment by qaiwiz** [comment]
thanks. will do.

**Comment by realyukii** [comment]
> If you’re using SSH as the proxy server, then you should know that it doesn’t support UDP, which causes this error.

I use the SOCKS server from [Dante](https://www.inet.no/dante/index.html), and it supports UDP, but I also get this warning: `client handshake: EOF`.
