### ISSUE TITLE
[Feature] Optional Features

### ISSUE THREAD

**Issue by Ali-Khazaee** [xjasonlyu/tun2socks#231]
### Description

I did compiled tun2socks for android the binary size is large approximate 30MB to support all arch.

While compiling tun2socks is it possible to disable unused parts ?

Depend on the developer to build only feature he wants like socks5 and disable other protocol like HTTP or ShadowSocks or etc

**Comment by xjasonlyu** [comment]
Yes, you can safely remove the unwanted transport/proxy protocols. But I don't think it will help to reduce binary size too much.
