### ISSUE TITLE
[Bug] DNS udp requests are shown in log but not resolved

### ISSUE THREAD

**Issue by pmartini** [xjasonlyu/tun2socks#232]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.4.1

### What OS are you seeing the problem on?

Linux

### Description

Hello
DNS queries are shown in tun2socks log, however dns requests are not resolved at all, neither curl domainname.com (curl: (6) Could not resolve host: ) or nslookup or any other, no response received. If use use raw ip address for http/https queries instead of domain name, everything works fine.
To fix this I had to add a route to 8.8.8.8 and 1.1.1.1 server through default enp0s3 interface to prevent routing via tun0, but it leads to dns leaks in browser which is not good. Is there a way to make dns requests work via tun2socks tunnel ? Forcing DNS vis TCP helps on local machine however other machines in 10.10.10.0 network can't be forced to use DNS over TCP.

### CLI or Config

ip a
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:a7:fe:3a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fea7:fe3a/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:ee:c8:e1 brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.1/24 brd 10.10.10.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:feee:c8e1/64 scope link 
       valid_lft forever preferred_lft forever
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 500
    link/none 
    inet 198.18.0.1/15 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::bebc:13c2:a2ee:3a19/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```
ip route
```
default via 198.18.0.1 dev tun0 metric 1 
default via 10.0.2.2 dev enp0s3 metric 10 
10.0.2.0/24 dev enp0s3 proto kernel scope link src 10.0.2.15 
10.10.10.0/24 dev enp0s8 proto kernel scope link src 10.10.10.1 
{{shadowsocksServerIp}} via 10.0.2.2 dev enp0s3 
198.18.0.0/15 dev tun0 proto kernel scope link src 198.18.0.1 

```

### Logs

```shell
INFO[0098] [UDP] 198.18.0.1:53561 <-> 8.8.8.8:53        
INFO[0099] [UDP] 198.18.0.1:53561 <-> 1.1.1.1:53        
INFO[0106] [UDP] 198.18.0.1:57242 <-> 8.8.8.8:53        
INFO[0107] [UDP] 198.18.0.1:57242 <-> 1.1.1.1:53        
INFO[0146] [UDP] 198.18.0.1:55278 <-> 8.8.8.8:53        
INFO[0147] [UDP] 198.18.0.1:55278 <-> 1.1.1.1:53        
INFO[0203] [UDP] 198.18.0.1:60976 <-> 8.8.8.8:53        
INFO[0204] [UDP] 198.18.0.1:60976 <-> 1.1.1.1:53        
INFO[0250] [UDP] 198.18.0.1:50277 <-> 8.8.8.8:53        
INFO[0251] [UDP] 198.18.0.1:50277 <-> 1.1.1.1:53        
INFO[0281] [UDP] 198.18.0.1:47553 <-> 1.1.1.1:53        
INFO[0286] [UDP] 198.18.0.1:45350 <-> 8.8.8.8:53        
INFO[0289] [UDP] 198.18.0.1:50625 <-> 8.8.4.4:53        
INFO[0302] [UDP] 198.18.0.1:55232 <-> 8.8.8.8:53        
INFO[0303] [UDP] 198.18.0.1:55232 <-> 1.1.1.1:53
```

### How to Reproduce
Download prebuild linux-amd64 binary version 2.4.1 and use on Debian 11 amd64, same if build from source code
_No response_

**Comment by xjasonlyu** [comment]
Thanks for your feedback! I would like to ask if your proxy server correctly supports the UDP relay. If not, you should try to use one.

However, if you just wanna DNS over tcp or whatsoever, you can install a DoH server locally. That will do all the magic.

**Comment by Ador-able** [comment]
我貌似遇到了同样的问题。
![ddc6492eee1c22174aa7dd9464e4c2c](https://user-images.githubusercontent.com/17660606/227428643-a4cfc0dc-35ef-44e4-9628-b8ba92f22cd0.png)
![bd4f4aa9c3c21e085ddc20786e10b9d](https://user-images.githubusercontent.com/17660606/227428675-08beabfa-ce04-4edb-b079-5b7ed51c49e4.png)
ping域名，日志正常显示，但是无法解析
![effd43227410d5718275f7f1a840671](https://user-images.githubusercontent.com/17660606/227428764-a2f9d2e5-0832-469e-887d-873d447980f5.png)
直接ping ip，是可以正常走代理的。

我是部署在docker desktop for window上的。代理是V2rayN.
我不太懂这些，怎么做才能正常dns解析呢？非常感谢

**Comment by Ador-able** [comment]
![image](https://user-images.githubusercontent.com/17660606/227446060-20c2c23e-3766-4e66-946b-33cfbee73dc5.png)
我写了一个脚本发送udp请求，通过代理去解析域名。在v2rayN中是能看到代理udp的相关日志的。

但是tun2socks发送的udp在v2rayN中看不到。好难，搞不懂。

**Comment by Ador-able** [comment]
@xjasonlyu 我使用python PySocks库写了一个测试脚本，其中通过代理发送udp流量，在tun2socks容器内部执行的。使用同样的代理地址，脚本发送的udp流量能被正确代理。经过tun2socks的udp流量 v2ray接收不到

**Comment by Ador-able** [comment]
![image](https://user-images.githubusercontent.com/17660606/227519667-9755b9be-49b0-4cb0-af54-0286dc0bb775.png)
![image](https://user-images.githubusercontent.com/17660606/227519732-b7cec9d0-3995-40c9-b333-0d95d46bf3ce.png)
是可以正常代理udp流量的

**Comment by Ador-able** [comment]
这是我在容器内部的测试脚本，v2rayn代理正常
`import socket
import socks

# 设置SOCKS5代理
socks.set_default_proxy(socks.SOCKS5, "192.168.65.2", 10808)

# 创建UDP socket
udp_socket = socks.socksocket(socket.AF_INET, socket.SOCK_DGRAM)

# 设置DNS解析请求数据
domain_name = "www.google.com"
dns_request = b"\xAB\xCD\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00" + \
              bytes([len(domain_name)]) + \
              domain_name.encode() + \
              b"\x00\x00\x01\x00\x01"

# 向8.8.8.8发送DNS解析请求
udp_socket.sendto(dns_request, ("8.8.8.8", 53))

# 接收DNS解析响应
data, address = udp_socket.recvfrom(1024)

# 解析DNS解析响应
ip_address = socket.inet_ntoa(data[-4:])

# 输出解析结果
print(f"解析结果：{ip_address}")

# 关闭UDP socket
udp_socket.close()`

**Comment by Ador-able** [comment]
@xjasonlyu 
![image](https://user-images.githubusercontent.com/17660606/227696293-28090e2c-5d90-440f-8cf2-08fb68258a1d.png)
确实是nat后的原因，socks5.go的123行，返回的代理 IP 地址是127.0.0.1，导致udp发错了。是否可以将127.0.0.1这种地址也走一下net.ResolveUDPAddr

**Comment by xjasonlyu** [comment]
这是不符合Socks5 UDP规范的，不应该更改tun2socks的代码，而应该是配置v2ray UDP的时候将监听地址绑定正确。

**Comment by coderchuan** [comment]
> [@xjasonlyu](https://github.com/xjasonlyu) ![image](https://user-images.githubusercontent.com/17660606/227696293-28090e2c-5d90-440f-8cf2-08fb68258a1d.png) 确实是nat后的原因，socks5.go的123行，返回的代理IP地址是127.0.0.1，导致udp发错了。是否可以将127.0.0.1这种地址也走一下net.ResolveUDPAddr

如果使用了 127.0.0.1 作为 socks 的服务地址，你应该再添加一个选项(如果是linux的话)，-interface lo
