### ISSUE TITLE
[Feature] socks5 failed to receive UDP multicast packets

### ISSUE THREAD

**Issue by snltty** [xjasonlyu/tun2socks#243]
### Description

我应该怎么做才能收到组播数据包呢，我调试了一下
![image](https://user-images.githubusercontent.com/10977033/231776541-ce092ace-22ec-49f9-9905-dcad0af4c6c6.png)
![image](https://user-images.githubusercontent.com/10977033/231776275-19d4a227-634c-4ec6-ac7f-5f9848a34e69.png)
打印了log，但是 socks5 没有收到数据包

**Comment by xjasonlyu** [comment]
代理似乎本身也不支持组播的吧

**Comment by snltty** [comment]
如果能收到数据包，我socks5代理可以手动广播给所有连接

**Comment by snltty** [comment]
是本身就没处理这些包吗，还是说是我设置的问题

**Comment by xjasonlyu** [comment]
我记得默认会忽略组播这些的

**Comment by xjasonlyu** [comment]
可以pr :)

**Comment by snltty** [comment]
go我看不太懂，不知道在哪处理，这就有点难了:)

**Comment by xjasonlyu** [comment]
@Mylodie PR is definitely welcome!

**Comment by snltty** [comment]
我的可以了，用了好像是2.4.1 还是2.4.0的版本，就能收到组播的包了 @Mylodie 
判断是否广播地址，直接广播出去就好了
![image](https://user-images.githubusercontent.com/10977033/232662327-ee1f0cef-07bd-4b74-97e5-639c7bb44994.png)

**Comment by xjasonlyu** [comment]
Hi @snltty @Mylodie,

Feel free to test Amaindex’s PR #245 if it meets all your requirements.

**Comment by snltty** [comment]
OK，I will try that

**Comment by Amaindex** [comment]
Hello @snltty @gleesheffle. Has anyone had a chance to try out [this patch](https://github.com/xjasonlyu/tun2socks/pull/245 )? Does it work well in your respective scenarios?

**Comment by xjasonlyu** [comment]
This issue might have been resolved already. Reopen it if needed.
