### ISSUE TITLE
[Bug] flag provided but not defined: -device

### ISSUE THREAD

**Issue by hosseinkhojany** [xjasonlyu/tun2socks#244]
### Verify steps

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.5.0

### What OS are you seeing the problem on?

Windows

### Description

C:\Users\hosse\Desktop\xray>tun2socks -device wintun -proxy socks5://127.0.0.1:10808
flag provided but not defined: -device

### CLI or Config

C:\Users\hosse\Desktop\xray>tun2socks -device wintun -proxy socks5://127.0.0.1:10808
flag provided but not defined: -device

### Logs

```shell
C:\Users\hosse\Desktop\xray>tun2socks -device wintun -proxy socks5://127.0.0.1:10808
flag provided but not defined: -device
```

### How to Reproduce

C:\Users\hosse\Desktop\xray>tun2socks -device wintun -proxy socks5://127.0.0.1:10808
flag provided but not defined: -device

**Comment by xjasonlyu** [comment]
I cannot reproduce this issue on my side. Could it be possibly caused by your shell interpreter?

**Comment by hosseinkhojany** [comment]
To use it in windows, download [wintun](https://www.wintun.net/) to the tun2socks folder or the system PATH and start the program.

![Screenshot 2023-04-18 124627](https://user-images.githubusercontent.com/37432839/232715670-15f6380d-1489-4654-bd1d-43b26f60f6f7.png)

Maybe wintun is not recognized
