### ISSUE TITLE
[Bug] Direct proxy mode does not work on macOS

### ISSUE THREAD

**Issue by Alkenso** [xjasonlyu/tun2socks#246]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.5.0

### What OS are you seeing the problem on?

macOS

### Description

I'm trying to run `tun2socks` tool in direct mode (without proxying)
In some reasons websites stops to work and I see lots of messages for both TCP and UDP like
```
WARN[0077] [UDP] dial 172.217.16.14:443: connect to direct: dial tcp: address direct: missing port in address
```

If I specify `socks5` proxy, all works like a charm

### CLI or Config

sudo ./tun2socks -device utun123 -proxy direct -interface en0

### Logs

```shell
WARN[0068] [TCP] dial 204.79.197.254:443: connect to direct: dial tcp: address direct: missing port in address 
WARN[0068] [TCP] dial 13.107.6.163:443: connect to direct: dial tcp: address direct: missing port in address 
WARN[0068] [TCP] dial 13.107.6.163:443: connect to direct: dial tcp: address direct: missing port in address 
WARN[0068] [TCP] dial 13.107.3.128:443: connect to direct: dial tcp: address direct: missing port in address 
WARN[0072] [UDP] dial 172.217.16.14:443: connect to direct: dial tcp: address direct: missing port in address 
WARN[0072] [UDP] dial 172.217.16.14:443: connect to direct: dial tcp: address direct: missing port in address
```

**Comment by xjasonlyu** [comment]
it’s `direct://`, not `direct` (this equals a domain called direct)

**Comment by Alkenso** [comment]
wow, missed reading docs. thank you!
