### ISSUE TITLE
[Bug] unable to send packets on OpenWRT

### ISSUE THREAD

**Issue by flakeforever** [xjasonlyu/tun2socks#254]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.5.0

### What OS are you seeing the problem on?

Other

### Description

I have been using 2.4.1 before, and it worked well on my OpenWRT(21.02.3). So when I updated to 2.5.0, in the same environment, I didn't change anything, I just replaced the file, then the tun device only has TX data but no RX data.

So even though I have set the log at debug level, it has no more output.

2.4.1
![2 4 1](https://github.com/xjasonlyu/tun2socks/assets/113103193/040b6327-89f8-40d2-975a-c2d6200dddae)

2.5.0
![2 5 0](https://github.com/xjasonlyu/tun2socks/assets/113103193/b2b97fcf-7523-4142-bd84-eb62ddfc564c)

I have briefly looked at the code, but it seems a bit complex to me. I would like to know where should I start if I want to investigate this issue myself.

Thank you, if someone could reply to me.

**Comment by xjasonlyu** [comment]
That's weird, v2.5.0 doesn't change anything on the tun side. Can you share your detailed configuration?

**Comment by flakeforever** [comment]
Alright, thank you.

My config:
/usr/sbin/tun2socks -device tun://tun0 -proxy socks5://10.8.0.7:1080 -loglevel debug

That's all, perhaps the issue lies in some default parameters?

**Comment by xjasonlyu** [comment]
How about your route tables?

**Comment by flakeforever** [comment]
Here is:

`ip rule add fwmark 100 lookup 100
ip route add default dev tun0 table 100
iptables -t mangle -A PREROUTING -s 192.168.10.128/26 -m set --match-set office-ip dst -j MARK --set-mark 100`

So, the office-ip is a ip-set

**Comment by myloft** [comment]
I had the same problem on an ARMv7 device.

**Comment by Kot-nikot** [comment]
Also release 2.5.0 does not work on OpenWRT 22.03 mipsel architecture. Installed 2.4.1 works.

**Comment by xjasonlyu** [comment]
Wondering how should I debug this as I don’t have arm-based openwrt devices. ;-)

**Comment by myloft** [comment]
From my test, the backend proxy server has received the request and returned the data. I will test on an x86 openwrt device to confirm whether it is related to the architecture.

**Comment by myloft** [comment]
> From my test, the backend proxy server has received the request and returned the data. I will test on an x86 openwrt device to confirm whether it is related to the architecture.

It works fine on an x86 openwrt device.

**Comment by Kot-nikot** [comment]
> Интересно, как мне отладить это, поскольку у меня нет устройств openwrt на базе рук. ;-)

does not work for me on ramips/mt7621

**Comment by xjasonlyu** [comment]
This issue should be fixed by 46c04db, welcome to try!

**Comment by xjasonlyu** [comment]
Yes, it is related to the wireguard tun module. I have tested on linux and macos, and it works well. But I have not yet tested on Windows.

Theoretically, if it shows TCP connections, then it should be fine..

**Comment by flakeforever** [comment]
Oh I mean it's an executable file, not .exe.  :)
It does show some TCP connections initially, but I believe it might be blocking the threads, causing the data not to be transmitted correctly. When I forcefully shut it down, I can see some information.

> DEBU[0123] [TCP] copy data for origin->remote: read tcp 142.251.220.110:443: operation aborted 
> DEBU[0123] [TCP] copy data for origin->remote: read tcp 104.244.42.193:443: operation aborted 
> DEBU[0123] [TCP] copy data for origin->remote: read tcp 13.251.235.250:443: operation aborted

**Comment by xjasonlyu** [comment]
Oh yes, these log messages are expected during shutdown stage.

**Comment by flakeforever** [comment]
After its initialization, it parsed some TCP connections, but these connections didn't finishe. It wasn't until I forcibly terminated it.

> INFO[0001] [TCP] 192.168.88.107:52626 <-> 142.251.220.110:443 
> INFO[0002] [TCP] 192.168.88.107:52629 <-> 104.244.42.193:443 
> INFO[0002] [TCP] 192.168.88.107:52630 <-> 104.244.42.193:443 
> INFO[0002] [TCP] 192.168.88.1:52631 <-> 104.244.42.193:443 
> INFO[0003] [TCP] 192.168.88.1:52637 <-> 13.251.235.250:443 
> INFO[0004] [TCP] 192.168.88.1:52638 <-> 104.244.42.2:443 
> INFO[0004] [TCP] 192.168.88.1:52639 <-> 104.244.42.2:443 
> INFO[0004] [TCP] 192.168.88.1:52640 <-> 104.244.42.2:443 

> DEBU[0123] [TCP] copy data for origin->remote: read tcp 142.251.220.110:443: operation aborted
> DEBU[0123] [TCP] copy data for origin->remote: read tcp 104.244.42.193:443: operation aborted
> DEBU[0123] [TCP] copy data for origin->remote: read tcp 13.251.235.250:443: operation aborted

**Comment by Kot-nikot** [comment]
I compiled the latest version of the package with yesterday's fixes for my linux mipsel platform:
tun2socks: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, Go BuildID=_a2qvyNQr2TsGApgkrYc/1HslD8tYyut90xLuuCH9/vs0I8gAVkClGIJVehn2Z/H_Sei_m7q3M2hukzwEWL, with debug_info, not stripped.

What do we have about the result:
The problem with data transfer is not solved. Some of the data passes through the tunnel and some does not.

INFO[0003] [TCP] 172.16.250.1:41708 <-> 157.240.205.34:443
INFO[0003] [TCP] 172.16.250.1:40764 <-> 157.240.205.63:443
INFO[0003] [TCP] 172.16.250.1:43832 <-> 31.13.65.50:80
DEBU[0075] [TCP] copy data for origin->remote: read tcp 31.13.65.50:80->172.16.250.1:43832: i/o timeout
DEBU[0130] [TCP] copy data for origin->remote: read tcp 157.240.205.63:443->172.16.250.1:40764: i/o timeout
DEBU[0333] [TCP] copy data for origin->remote: read tcp 157.240.205.34:443: operation timed out
DEBU[0393] [TCP] copy data for remote->origin: read tcp 100.81.8.82:38240->141.148.224.141:1234: i/o timeout

Accordingly, resources in the network are not available.

**Comment by netrixken** [comment]
can confirm, latest source code still has the issue (mt7621)

**Comment by xjasonlyu** [comment]
OK, I'll check it again.

**Comment by xjasonlyu** [comment]
Can anyone confirm this fix: https://github.com/xjasonlyu/tun2socks/commit/a910fb20574eda9eb46127e88978779de97153cc?

**Comment by flakeforever** [comment]
Okay, cool bro! I confirm that this issue has been resolved.
