### ISSUE TITLE
Reverse socks2tun implementation

### ISSUE THREAD

**Issue by undiabler** [xjasonlyu/tun2socks#26]
I'm looking for reverse implementation converting many vpn/wireguard interfaces to socks5 proxy.
For now I have plenty of hacks running lots of different socks servers via different users, then marking and properly routing traffic using iptables. All this stuff is very unstable.

Can you give me advise how network interfaces can be converted into socks5 proxy in easiest way?
Thanks!

**Comment by xjasonlyu** [comment]
What do you mean `convert interfaces to socks5 proxy`?

Could you give me more context or examples?

**Comment by undiabler** [comment]
I want to use any existing network interface as socks5 proxy.
For example curl can make http(s) request via selected interface with --interface parameter.

There are lots of applications supporting socks4/5 options. I want to have different vpn-s for different applications.
I can reach this goal by seperating each application in different network environment as qubes os do. But the easiest way is to create socks server for each network interface (tun/tap/wg device).

**Comment by xjasonlyu** [comment]
Your needs are not related to this `tun2socks` project, but it's doable. A simple socks/http proxy server with `BINDTODEVICE` support would do the trick (I guess🙈).

**Comment by undiabler** [comment]
I have not found any simple socks/http proxy with `BINDTODEVICE` support.
So I've implemented such trick for [usocksd socks server](https://github.com/cybozu-go/usocksd).
Thanks for your help.

**Comment by ValdikSS** [comment]
> I have not found any simple socks/http proxy with `BINDTODEVICE` support.

Just for the record, I usually use https://3proxy.org/ as a proxy with outgoing ip/interface functionality.
