### ISSUE TITLE
[Feature] Multiple tun-post-up arguments

### ISSUE THREAD

**Issue by Saeed-Pooyanfar** [xjasonlyu/tun2socks#265]
### Description

In windows after setting up tun interface (by running tun2socks itself) we need 3 commands to execute (netsh) :  
1- For assigning IP address to tun
2- Set primary DNS
3- Set secondary DNS
It seems that tun-post-up only accept 1 command and if i try to pass multiple commands with `&&`
It ignores the whole command and doesn't execute anything
So please add a feature that we can pass multiple tun-post-up:  
`tun2socks ... -tun-post-up "%TUN_IP%" -tun-post-up "%TUN_FIRST_DNS%" -tun-post-up "%TUN_SECOND_DNS%"`
Or please add support for `&&`:  
`tun2socks ... -tun-post-up "%TUN_IP% && %TUN_FIRST_DNS% && %TUN_SECOND_DNS%"`

**Comment by xjasonlyu** [comment]
You can use a cmd/bat script to do this. 😉

**Comment by Saeed-Pooyanfar** [comment]
> You can use a cmd/bat script to do this. wink

Yeah, but since `tun2socks` is a blocking command and it creates the tun interface i have to run it in background
Then i can't run `netsh ...` immediately to set ip or dns because the interface needs time to create
So i have to use something like timeout command (1 or 2 seconds)
In this way i don't need `-tun-post-up` at all  
(I wish if i could use tun-post-up to not using timeout command)

**Comment by xjasonlyu** [comment]
Oh, I mean you can use a cmd/bat script like: `-tun-post-up <your_script.bat>`

**Comment by Saeed-Pooyanfar** [comment]
> Oh, I mean you can use a cmd/bat script like: `-tun-post-up <your_script.bat>`

Thanks, but
I wrote a script ([socks2vpn.bat](https://gist.github.com/Saeed-Pooyanfar/b805a22e7c64723f0c3c4f2057e3bfb0#file-socks2vpn-bat)) to make the setup a little bit easier  
Your suggest may work, but I have to create another script which is not sounds good to me  
Currently used the timeout command and it's working fine
