### ISSUE TITLE
[Bug] [Documentation] Specified minimum Go version is too low - 1.20 is required to build from source.

### ISSUE THREAD

**Issue by ddscentral** [xjasonlyu/tun2socks#274]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

HEAD (8309fdd)

### What OS are you seeing the problem on?

Linux

### Description

Your [documentation](https://github.com/xjasonlyu/tun2socks/wiki/Install-from-Source) specifies that the minimum version to build from source is 1.18, which is what is shipped with Ubuntu 22.04. But some dependencies (for example, the gVisor module) which you use require Go 1.20  to build and will not build with Ubuntu's Go 1.18.
 
You need to either correct your documentation that the minimum version to build is Go 1.20 or later or downgrade your dependencies to something that will build with Go 1.18.

Everything builds fine with Go 1.20.5.

### How to Reproduce

Try to build on Ubuntu 22.04 with golang package installed.

**Comment by xjasonlyu** [comment]
Thanks for the reminder. The wiki doc has been fixed!
