### ISSUE TITLE
DNS over HTTPS?

### ISSUE THREAD

**Issue by Manouchehri** [xjasonlyu/tun2socks#28]
Is it possible to use DNS over HTTPS with tun2socks? I see some code is there, but not sure how I'm supposed to set the upstream DNS server.

https://github.com/xjasonlyu/tun2socks/blob/fcf9d280b84632053f5afd8a1fe9668193c16362/internal/dns/utils.go#L109-L126

```
dave@xps:~/tun2socks/bin$ ./tun2socks-linux-amd64 --loglevel debug --device tun://tun0 --proxy socks5://127.0.0.1:8080 --dns https://1.1.1.1
FATA[0000] Failed to start: start DNS server https://1.1.1.1: unsupported scheme 
```

Thanks!

**Comment by xjasonlyu** [comment]
To specify parameters, the correct way is adding them as url key-value pairs. In this case is `dns://listen_ip:port/?nameserver=...`, and be aware of url escape/encodings.

BTW, the DNS support might be deprecated in the future. tun2socks should only focus on its own job, let upstream proxy server take care of the rest.

**Comment by xjasonlyu** [comment]
DNS mode has been removed after `v2.1.0`.

**Comment by Manouchehri** [comment]
For anyone else who happens to run across this ticket, I switched to using CoreDNS. 🙂

**Comment by xjasonlyu** [comment]
Right! CoreDNS is awesome!👍

**Comment by Manouchehri** [comment]
Another update for others, you can also use DNS over TCP too if you don't want to use DoT or DoH.

`resolv.conf`
```
options use-vc
nameserver 1.1.1.1
nameserver 8.8.8.8
```
