### ISSUE TITLE
[Feature] DNS Forwarder

### ISSUE THREAD

**Issue by xtianxian** [xjasonlyu/tun2socks#287]
### Description

Hi xjasonlyu,

Is there an way to easily I can forward DNS request to an upstream DNS server e.g. pdns, coredns, or to DOT, DOH using this tun2socks. btw i'm using it in Android vpn service.

### Is this feature related to a specific bug?

No.

### Do you have a specific solution in mind?

in the other tun2socks there is an option --dnsgw <dns_gateway_address> to where the dns request is forwarded.

**Comment by xjasonlyu** [comment]
Are you looking for the [DNS hijack](https://github.com/xjasonlyu/tun2socks/wiki/Hijack-DNS)?

**Comment by xtianxian** [comment]
Yes. So i guess it is not possible for non rooted android device since iptables require root. Any plans of putting back FakeDns feature in the latest version? 

By the way, thanks for the great work on this project i think it is the best tun2socks.
