### ISSUE TITLE
[Feature] [Bounty $100] FakeDNS

### ISSUE THREAD

**Issue by KnockKnockWho** [xjasonlyu/tun2socks#293]
Unfortunately, the use of tun2socks requires users to rely on third-party DNS resolvers, even when UDP is supported. At the risk of being a duplicate of #287, this feature request specifically requests to bring back the "fakedns" feature, such that DNS is resolved by the proxy.

I have specifically created this issue to be able to assign a bounty. I offer **50 USD to anyone that gets a pull request with that functionality merged** through [Bountysource](https://app.bountysource.com/issues/123832281-feature-fakedns).

Direct link to the bounty: https://app.bountysource.com/issues/123832281-feature-fakedns

The bounty is not too much, but there are forks lying around that already implement this feature. Their code might just require some cleanup.

**Comment by xjasonlyu** [comment]
Hoping someone can submit a pr for this feature. 😉

I currently don't have time for it.

**Comment by Vayras** [comment]
Hi @KnockKnockWho  I'm new to learning Go-lang and I wish to try and solve this issue I personally do not care about the bounty can you please tell me what files and the workflow associated with this so I can perform a cleanup or fix this?

**Comment by xjasonlyu** [comment]
I would recommend to implement this functionality based on Clash's [fake dns module](https://github.com/Dreamacro/clash/tree/master/component/fakeip).

**Comment by abebeos** [comment]
- https://github.com/bountysource/core/issues/1586

**Comment by abebeos** [comment]
> b) try to get the money I paid to BountySource back through PayPal's buyer protection.

There a thousands of $ unpaid since months, so you should use buyer protection now.

**Comment by planetoryd** [comment]
I have implemented tun2socks (with virtual DNS) and netns containerization feature in https://github.com/planetoryd/nsproxy
