### ISSUE TITLE
功能增强， TUN 接口（虚拟网卡）的 IP 设置，和网关设置。

### ISSUE THREAD

**Issue by sdfsdfsdf145314364** [xjasonlyu/tun2socks#30]
希望能增加这两个功能，此功，在win上是必不可少的，能直接设置最好，可以让使用者减轻很多麻烦。

-tunAddr 10.0.0.2 -tunGw 10.0.0.1  如其他版本tun2socks一样。

**Comment by xjasonlyu** [comment]
目前考虑到多系统的兼容性，设置接口地址建议直接通过脚本来一并解决（包括路由表的配置）。

只要一条命令就可以配置接口地址`netsh interface ip set address <interface> static <address> <netmask>`，网关地址可以不用设置。

**Comment by f4nff** [comment]
`设置接口地址建议直接通过脚本来一并解决（包括路由表的配置）。`

表示非常认同，
