### ISSUE TITLE
[Bug] wintun device name incorrect in Windows

### ISSUE THREAD

**Issue by sonvirgo** [xjasonlyu/tun2socks#300]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.5.1

### What OS are you seeing the problem on?

Windows

### Description

The created tun interface change its name by adding increasing number
ie wintun1, wintun2, wintun3, ...

This affect NAT internet sharing from the wintun interface to Hotspot   

![Screenshot (18)](https://github.com/xjasonlyu/tun2socks/assets/10823037/a87f6a54-455c-4d94-b016-17b86650edbb)

### CLI or Config

tun2socks-windows-amd64 -device tun://wintun -proxy socks5://127.0.0.1:1081

### How to Reproduce

just run the coomand
wintun change its name every time

**Comment by xjasonlyu** [comment]
This should be fixed by #301. Please feel free to reopen it if this issue still exists!

By specifying the GUID for wintun adapters, see [tun-options](https://github.com/xjasonlyu/tun2socks/wiki/Device-Models#tun-options).

**Comment by sonvirgo** [comment]
> This should be fixed by #301. Please feel free to reopen it if this issue still exists!
> 
> To specify the GUID for wintun adapters, see [tun-options](https://github.com/xjasonlyu/tun2socks/wiki/Device-Models#tun-options).

Thank buddy, but where is the new build for device model?

**Comment by xjasonlyu** [comment]
There's no release yet, but you can build yourself.

**Comment by sonvirgo** [comment]
> There's no release yet, but you can build yourself.

clone the repo then build but error on run 
![Screenshot (6)](https://github.com/xjasonlyu/tun2socks/assets/10823037/b2877b0c-ddba-4371-bf24-7c636bafb916)

**Comment by sonvirgo** [comment]
> There's no release yet, but you can build yourself.

Thanks, works as expected
