### ISSUE TITLE
udp not working

### ISSUE THREAD

**Issue by rudius** [xjasonlyu/tun2socks#31]
i m trying v2.1.0 linux amd64 with command ./tun2socks-linux-amd64 -device tun://tun0 -proxy socks5://127.0.0.1:1080

 I m routing all traffic from another linux on the network to the tun interface.

Tcp is working great but udp is not working at all.

i ve got this

WARN[7446] [UDP] write to 1.1.1.1:53 error: write udp [::]:40930->127.0.0.1:0: sendto: invalid argument 
INFO[7446] [UDP] 192.168.0.35:34418 --> 1.1.1.1:53

**Comment by xjasonlyu** [comment]
Would mind to tell which socks5 server you were using with?

It’s wired that your server sent `127.0.0.1:0` as bind address in UDP.

**Comment by rudius** [comment]
it shadowproxy_libev on port 1080.

i just did ip link set dev tun0 up. I didn t attached an ip to it and my routes were going to dev tun0. Maybe it s that? TCP is working though

**Comment by xjasonlyu** [comment]
> i just did ip link set dev tun0 up. I didn t attached an ip to it and my routes were going to dev tun0. Maybe it s that? TCP is working though

No, tun doesn’t need a ip address could still work if you have route table to it.

BTW, what is `shadowproxy_libev`? Do you mean `shadowsocks_libev`, if it is then which version of it?

**Comment by rudius** [comment]
yes it s shadowsocks-libev V3.1.3 on ubuntu 18.04

**Comment by xjasonlyu** [comment]
It seems like a server side issue due to wrong bind-address of UDP. You may need to upgrade ss-libev to latest version (v3.3.5 now) since a lot UDP issues have been resolved.

If this bug still exists, please let me know.

**Comment by rudius** [comment]
currently doing the update. I will let you know

**Comment by rudius** [comment]
you were right. It s working. Thanks
