### ISSUE TITLE
[Feature] Do not accept connection locally before connection with remote is established

### ISSUE THREAD

**Issue by janedoe-lab** [xjasonlyu/tun2socks#320]
### Description

Currently, when proxied application makes a connection, it immediately succeeds as if port is always open. This works very differently from proxychains, which waits to establish connection with the remote. It is a subtle difference, but it breaks software that needs to check if port is truly open.

Is it possible with current tun2socks architecture to implement feature (or is this a bug?) where tun2socks would first try to connect to the port, and only if it succeeds, report success on the client side?

**Comment by xjasonlyu** [comment]
This feature has been mentioned in issue https://github.com/xjasonlyu/tun2socks/issues/83, and we have a closed/incomplete pr https://github.com/xjasonlyu/tun2socks/pull/235 for this kind of scenario.

Unfortunately, this feature is not yet planned to implement. But if you would like to contribute, a pr is always welcome!
