### ISSUE TITLE
failed to set MTU of TUN device: invalid argument

### ISSUE THREAD

**Issue by atong027** [xjasonlyu/tun2socks#33]
root@p722:/online # ./tun2socks -device tun://tun0 -proxy socks5://127.0.0.1:10808
FATA[0000] Failed to start engine: create tun: failed to set MTU of TUN device: invalid argument

**Comment by xjasonlyu** [comment]
Which platform you're running?

**Comment by xjasonlyu** [comment]
temporary workaround: add MTU, e.g. `-mtu 1500`

**Comment by slrslr** [comment]
> temporary workaround: add MTU, e.g. `-mtu 1500`

I am also getting [create tun "invalid argument" error](https://github.com/xjasonlyu/tun2socks/discussions/295#discussioncomment-6933955) and Yours mentioned -mtu not prevented it.
