### ISSUE TITLE
[Bug] cannot ssh to remote server

### ISSUE THREAD

**Issue by SigmaStar** [xjasonlyu/tun2socks#330]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

latest

### What OS are you seeing the problem on?

Linux

### Description

I set up tun2sock for a server as example did but I found I cannot ssh to the server anymore. In IPMI web view i can access bing.com, i can ping and wget main page. but i can not ssh to that server.

### CLI or Config

non

### Logs

```shell
non
```

### How to Reproduce

non

**Comment by xjasonlyu** [comment]
Please provide more information so that I can help to solve the issue.

**Comment by SigmaStar** [comment]
I want to setup tun2socks on server 1 so I did as what tutorial shows. The socks5 proxy is running on my workstation and is used for server 1.


By the time I finished tun2socks configuration and start running tun2sock I found my ssh connection to the server 1 disconnected. But I can connect to the Internet on server 1.&nbsp;



---Original---
From: "Jason ***@***.***&gt;
Date: Tue, Feb 20, 2024 04:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xjasonlyu/tun2socks] [Bug] cannot ssh to remote server (Issue#330)




 
Please provide more information so that I can help to solve the issue.
