### ISSUE TITLE
[Bug] -tcp-sndBuf does not appear to change the send buffer size on Linux

### ISSUE THREAD

**Issue by niconorsk** [xjasonlyu/tun2socks#335]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.5.1

### Description

When starting tun2socks with the -tcp-sndbuf argument, this does not actually appear to work.  The command runs fine but if I look at the strace output the SO_SNDBUF getsockopt option is never called.

I've done a dive in the source code and have found one bug in `core/tcp.go` however even with this fix, it still does not actually seem to change the senb buffer size

```
diff --git a/core/tcp.go b/core/tcp.go
index 7195fa1..f387f8f 100644
--- a/core/tcp.go
+++ b/core/tcp.go
@@ -101,12 +101,14 @@ func setSocketOptions(s *stack.Stack, ep tcpip.Endpoint) tcpip.Error {
        { /* TCP recv/send buffer size */
                var ss tcpip.TCPSendBufferSizeRangeOption
                if err := s.TransportProtocolOption(header.TCPProtocolNumber, &ss); err == nil {
-                       ep.SocketOptions().SetReceiveBufferSize(int64(ss.Default), false)
+                       ep.SocketOptions().SetSendBufferSize(int64(ss.Default), false)
                }
```

I'm happy to test any other suggested fixes but further understanding is a bit beyond me

**Comment by xjasonlyu** [comment]
Hi there,

The `-tcp-sndbuf` argument is used to set the send buffer size of the internal/userspace gVisor TCP/IP stack, and it doesn't affect the Linux kernel setting. That's why there is no output on the strace.

**Comment by xjasonlyu** [comment]
But apparently there is a bug on this line:

https://github.com/xjasonlyu/tun2socks/blob/2334083cf9b8afea7caf7679a17e66b6d15c504e/core/tcp.go#L104

And you are welcome to submit a PR to fix it. :-P
