### ISSUE TITLE
[Bug] param -tun-post-up not work

### ISSUE THREAD

**Issue by iLemonRain** [xjasonlyu/tun2socks#338]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

v2.5.2

### What OS are you seeing the problem on?

Windows

### Description

try to use the param -tun-post-up to attach the path of bat script
the content of that script was like "echo hello"
but no that output in terminal while no error showed
please teach me how to use this param correctly
Thank you!
or please tell me how another way to know if TUN device is ready to use:-)

**Comment by xjasonlyu** [comment]
`-tun-post-up' will execute the given commands, but there would be no output (this is by design).

It can be used like `-tun-post-up "sh some_script.sh"`.

> or please tell me how another way to know if TUN device is ready to use :-)

`-tun-post-up` is always executed after TUN is ready.

Cheers.

**Comment by iLemonRain** [comment]
> `-tun-post-up` will execute the given commands, but there would be no output (this is by design).
> 
> It can be used like `-tun-post-up "sh some_script.sh"`.
> 
> > or please tell me how another way to know if TUN device is ready to use :-)
> 
> `-tun-post-up` is always executed after TUN is ready.
> 
> Cheers.

Thanks.
And how to understand "TUN is ready"？
I don’t know if there are any standards

**Comment by xjasonlyu** [comment]
Ready basically means the TUN interface is created and you can see the link is up in Linux (using `ifconfig`).

**Comment by xjasonlyu** [comment]
Feel free to check this <https://github.com/xjasonlyu/tun2socks/wiki/TUN-Pre-and-Post-UP>.
