### ISSUE TITLE
运行后一接到数据包就退出

### ISSUE THREAD

**Issue by ddiiccoo** [xjasonlyu/tun2socks#34]
运行平台：WIN10 X64
代理协议：SOCKS5
TUN2SOCKS版本号：2.1.3
过程：
tun2socks -device tun://tun0 -proxy socks5://127.0.0.1:1080 -mtu 1500 -udp-timeout 1000  #这里1080为V2RAY监听的SOCKS5端口
结果：虚拟网卡接收到数据，但立即程序就退出了。日志如下。
goroutine 330 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Store64(0x11c1a41c, 0x100000, 0x0)
        runtime/internal/atomic/asm_386.s:213 +0x10
gvisor.dev/gvisor/pkg/tcpip.(*SocketOptions).SetSendBufferSize(0x11c1a3b0, 0x100000, 0x0, 0x5a47cc00)
        gvisor.dev/gvisor@v0.0.0-20210220013851-93fc09248a2f/pkg/tcpip/socketops.go:607 +0x141
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.newEndpoint(0x119a8000, 0x800, 0x118a5b00, 0x4)
        gvisor.dev/gvisor@v0.0.0-20210220013851-93fc09248a2f/pkg/tcpip/transport/tcp/endpoint.go:890 +0x1e5
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).createConnectingEndpoint(0x119cc000, 0x1180e280, 0xc4def287, 0x9ee5abab, 0x119e5f70, 0x118a5b00, 0xc6f77e98, 0xc4def287, 0x0)
        gvisor.dev/gvisor@v0.0.0-20210220013851-93fc09248a2f/pkg/tcpip/transport/tcp/accept.go:214 +0xa9
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).startHandshake(0x119cc000, 0x1180e280, 0x119e5f70, 0x118a5b00, 0x0, 0x0, 0x0, 0x0, 0x0)
        gvisor.dev/gvisor@v0.0.0-20210220013851-93fc09248a2f/pkg/tcpip/transport/tcp/accept.go:249 +0xb3
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).performHandshake(0x119cc000, 0x1180e280, 0x119e5f70, 0x118a5b00, 0x0, 0x0, 0x18, 0x7902d8, 0x0)
        gvisor.dev/gvisor@v0.0.0-20210220013851-93fc09248a2f/pkg/tcpip/transport/tcp/accept.go:317 +0x69
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*ForwarderRequest).CreateEndpoint(0x11843ad0, 0x118a5b00, 0x0, 0x0, 0x0, 0x0)        gvisor.dev/gvisor@v0.0.0-20210220013851-93fc09248a2f/pkg/tcpip/transport/tcp/forwarder.go:155 +0xf3
github.com/xjasonlyu/tun2socks/core/stack.withTCPHandler.func1.1(0x11843ad0)
        github.com/xjasonlyu/tun2socks/core/stack/tcp.go:40 +0x8a
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket
        gvisor.dev/gvisor@v0.0.0-20210220013851-93fc09248a2f/pkg/tcpip/transport/tcp/forwarder.go:94 +0x1f4

**Comment by xjasonlyu** [comment]
你好像是是64位的windows下了32位版本的tun2socks了。

**Comment by ddiiccoo** [comment]
> 你好像是是64位的windows下了32位版本的tun2socks了。

感谢，果然是这样。

**Comment by xjasonlyu** [comment]
> X'07' Command not supported

你的socks5代理服务器不支持`UDP Associate`命令

**Comment by xjasonlyu** [comment]
你是不是v2ray没开UDP选项？

**Comment by ddiiccoo** [comment]
> 你是不是v2ray没开UDP选项？

是的，我的确用的V2RAY.但是请问是什么参数控制的打开呢？

**Comment by xjasonlyu** [comment]
https://www.v2ray.com/en/configuration/protocols/socks.html

```json
{
  "auth": "noauth",
  "accounts": [
    {
      "user": "my-username",
      "pass": "my-password"
    }
  ],
  "udp": true,
  "ip": "127.0.0.1",
  "userLevel": 0
}
```

注意IP那里要填对，不然发不过去。

**Comment by ddiiccoo** [comment]
> https://www.v2ray.com/en/configuration/protocols/socks.html
> 
> ```json
> {
>   "auth": "noauth",
>   "accounts": [
>     {
>       "user": "my-username",
>       "pass": "my-password"
>     }
>   ],
>   "udp": true,
>   "ip": "127.0.0.1",
>   "userLevel": 0
> }
> ```
> 
> 注意IP那里要填对，不然发不过去。

谢谢，搞定了！非常感谢楼主的大力帮助

**Comment by ddiiccoo** [comment]
> 你是不是v2ray没开UDP选项？

最后有一个疑问就是每次启动了后，打开浏览器访问网站都是刚开始要等待很久大概30秒才能真正打开网页。后面就好了。只是刚开始这样。网上说是系统的什么网络检测服务导致的。不知道您是否遇到过这个问题

**Comment by xjasonlyu** [comment]
应该是你配置的问题，没有详细的信息我也不知道为啥🌚

**Comment by ddiiccoo** [comment]
```
{
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "127.0.0.1",
        "userLevel": 0
      }
    },
    {
      "port": 1000,
      "protocol": "http",
      "settings": {}
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxx.com",  #省略
            "port": 443,
            "users": [
              {
                "id": "xxx",   #省略
                "alterId": 0,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls"
      },
      "mux": {
        "enabled": true
      }
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn",
          "geoip:private"
        ]
      }
    ]
  }
}

```
这是我 客户端 的配置
