### ISSUE TITLE
程序在WIN7x32系统下无法运行

### ISSUE THREAD

**Issue by ddiiccoo** [xjasonlyu/tun2socks#37]
经测试，在WIN7x86系统下，由于wintun.dll的原因，无法运行，也无法安装虚拟网卡，如下文字：
Error loading wintun.dll DLL: Unable to load library: The parameter is incorrect.
意思是wintun.dll版本好像不对。但是我去wintun官网下载了最新版本的wintun.dll，版本0.10.2。官方提供的x86的DLL，包括压缩包里的其他DLL我都试了一遍，全部都出现这个错误提示

**Comment by xjasonlyu** [comment]
https://github.com/tailscale/tailscale/issues/1051

参考这个，要打补丁。

**Comment by ddiiccoo** [comment]
按照那个帖子打了补丁仍然不行，还是这个错误。

**Comment by xjasonlyu** [comment]
> Windows 7, Windows Server 2008 R2, Windows Vista and Windows Server 2008:  This value requires [KB2533623](https://support.microsoft.com/kb/2533623) to be installed.

装完可能需要重启。

**Comment by xjasonlyu** [comment]
原因是win7 EOL了，本身不支持这个参数，需要打补丁。

**Comment by ddiiccoo** [comment]
> > Windows 7, Windows Server 2008 R2, Windows Vista and Windows Server 2008:  This value requires [KB2533623](https://support.microsoft.com/kb/2533623) to be installed.
> 
> 装完可能需要重启。

我重启了的，还是一样的。哎，这挺可惜的

**Comment by xjasonlyu** [comment]
你装的是这个补丁嘛🤔

**Comment by ddiiccoo** [comment]
> 你装的是这个补丁嘛

是的，按照帖子中的链接
https://download.wireguard.com/windows-toolchain/distfiles/Windows6.1-KB2921916-x86.msu
重启后仍然不行。看来真的是那个库的问题了。

**Comment by xjasonlyu** [comment]
不，是

https://support.microsoft.com/kb/2533623

**Comment by ddiiccoo** [comment]
> 不，是
> 
> https://support.microsoft.com/kb/2533623

哦，难怪。但万恶的微软好像已经不给下载了，郁闷

**Comment by xjasonlyu** [comment]
google找野生资源，或者，别用win7。。

**Comment by ddiiccoo** [comment]
> google找野生资源，或者，别用win7。。

谢谢 ，已经找到。经测试，的确可行
