### ISSUE TITLE
[Feature] adding TCP_NODELAY option for socks5

### ISSUE THREAD

**Issue by mtnkm** [xjasonlyu/tun2socks#386]
### Description

Hello,
By adding TCP_NODELAY to the socks proxy server and incorporating this option into the project through loading LD_PRELOAD, I was able to achieve greater agility in the connections.

Is it possible to add this option for outgoing local TCP connections? 
Something like 
-tcpnodelay

### Is this feature related to a specific bug?

no

### Do you have a specific solution in mind?

adding tcpnodelay to outgoing tcp connection as an option

**Comment by xjasonlyu** [comment]
TCP NO DELAY is enabled by default in tun2socks. :)
