### ISSUE TITLE
关于ICMP/ICMP6代理

### ISSUE THREAD

**Issue by cyznke** [xjasonlyu/tun2socks#39]
您好，我想将ICMP封装到UDP中通过代理出去，看了一遍代码也没明白该从何处下手修改获取ICMP，您能否提供一些参考建议？

**Comment by xjasonlyu** [comment]
ICMP是网络栈gVisor自己处理的。

https://github.com/xjasonlyu/tun2socks/blob/f41b844e43fb1e4eec16e1e4ee5d05255d02f500/core/stack/icmp.go#L10-L21

如果你要改的话，在`tun`实现后用`rwbased`模块，直接处理读出来的是否为ICMP包，然后hook出来。

https://github.com/xjasonlyu/tun2socks/blob/f41b844e43fb1e4eec16e1e4ee5d05255d02f500/core/device/rwbased/endpoint.go#L57-L81

不过个人感觉ICMP走UDP意义不大？（需要自己实现一个远端去转发ICMP）🤔，不如直接用wg或者ovpn仅代理ICMP然后走tun2socks或者直接socks出去。

**Comment by cyznke** [comment]
好的，我这边试试看看能不能搞

**Comment by johnnyhansen-away** [comment]
请问最后搞定icmp的代理了么
