### ISSUE TITLE
[Bug] Memory leaks on Windows 11 using Tun2socks 2.5.2 (wintun 0.14.1) with Xray 1.8.17

### ISSUE THREAD

**Issue by tw0ch** [xjasonlyu/tun2socks#390]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### Version

2.5.2

### What OS are you seeing the problem on?

Windows

### Description

I am faced with the problem of large memory leaks when using the Xray-client with tun2socks (for local socks proxy) on Windows 11, here is my Xray config:

<details><summary>Xray-client config.json</summary><pre><code>{
  "dns": {
    "disableCache": true,
    "hosts": {
      "one.one.one.one": [
        "1.1.1.1"
      ]
    },
    "queryStrategy": "UseIPv4",
    "servers": [
      {
        "address": "https://one.one.one.one/dns-query"
      },
      {
        "address": "https+local://dns.quad9.net/dns-query",
        "domains": [
          "regexp:\\.ru$",
          "geosite:category-gov-ru",
          "geosite:yandex",
          "geosite:mailru"
        ]
      },
      "1.1.1.1"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    }
  ],
  "log": {
    "dnsLog": true,
    "loglevel": "debug"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": 8,
        "enabled": false
      },
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "<tt>my-server-address</tt>",
            "port": 443,
            "users": [
              {
                "encryption": "none",
                "flow": "xtls-rprx-vision",
                "id": "<tt>my-server-id</tt>",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "realitySettings": {
          "allowInsecure": false,
          "fingerprint": "chrome",
          "publicKey": "<tt>my-server-key</tt>",
          "serverName": "<tt>my-server-name</tt>",
          "shortId": "<tt>my-server-short-id</tt>",
          "show": false,
          "spiderX": ""
        },
        "security": "reality",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      },
      {
        "inboundTag": [
          "dnsQuery"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "outboundTag": "dnsOut",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "outboundTag": "block",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "ip": [
          "geoip:ru"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "regexp:\\.ru$"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:category-gov-ru"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:yandex"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:mailru"
        ],
        "outboundTag": "direct",
        "type": "field"
      }
    ]
  }
}</code></pre></details>

Leaks reaches **2GB+** on Tun2socks.exe and **1GB+** on Xray.exe

![tun2socks-memory-leak](https://github.com/user-attachments/assets/9adc68ce-34fe-4958-86e0-742f155342b3) 
![xray-memory-leak](https://github.com/user-attachments/assets/f6f27435-2741-4c76-8447-44b3c359b8f8)

I guess my virtual adapter is being created incorrectly in some way and traffic just starts to overflow the Tun2socks and Xray stacks. Maybe someone can provide me with other tools for local socks-proxying to the xray-client (at 127.0.0.1:10808) I will be very grateful! 

### CLI or Config

<pre><code>.\tun2socks.exe -device tun-device -proxy 127.0.0.1:10808
</code></pre>

### Logs

```shell
[Tun2socks] time="2024-08-16T10:48:56+03:00" level=warning msg="[UDP] dial "server-ip": connect to 127.0.0.1:10808: dial tcp 127.0.0.1:10808: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."
[Tun2socks] time="2024-08-16T10:48:58+03:00" level=warning msg="[UDP] dial "server-ip": connect to 127.0.0.1:10808: dial tcp 127.0.0.1:10808: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted."
```

### How to Reproduce

1. In cmd run Xray-core as admin with config from the description :
<pre><code>.\xray.exe</code>
</pre>

2. In another cmd run Tun2socks as admin:
<pre><code>.\tun2socks.exe -device tun-device -proxy 127.0.0.1:10808
</code></pre>

3. In another cmd configure the virtual adapter:
<pre><code>netsh interface ip set address name=tun-device addr=10.0.236.10 source=static mask=255.255.255.0 gateway=none
</code></pre>

4. Set DNS from the xray-config for tun-device:
<pre><code>netsh interface ip set dns name=tun-device static <tt>(dns-ip-address, ex: 1.1.1.1)</tt>
</code></pre>

5. Adding routes to the local DNS table:
<pre><code>route add <tt>(xray-server-ip, ex: 172.210.11.100)</tt> mask 255.255.255.255 <tt>(windows-default-gateway-ip, ex: 192.168.0.1)</tt>
</code></pre>
<pre><code>route add 0.0.0.0 mask 0.0.0.0 10.0.236.10
</code></pre>

**Comment by xjasonlyu** [comment]
Just wondering, were you able to connect to internet after your setup using tun2socks and xray?

**Comment by DevourerPi** [comment]
> Just wondering, were you able to connect to internet after your setup using tun2socks and xray?

![image](https://github.com/user-attachments/assets/6f76c9b3-ec02-4330-9970-61e7b09898c9)

I tried the same operation as described in the problem, and yes, it can connect to the network:

![image](https://github.com/user-attachments/assets/f72f6c3e-24ed-40c6-86c0-765204981d6f)

**Comment by tw0ch** [comment]
Yes, it was successful, what could be the problem?
