### ISSUE TITLE
FakeDNS Option

### ISSUE THREAD

**Issue by entianbucali** [xjasonlyu/tun2socks#40]
Would it be possible to include the FakeDNS option which would allow for remote DNS use in socks 5 proxies. Thanks

**Comment by xjasonlyu** [comment]
Maybe it’s a little hacky, but using some special proxy server like [clash](https://github.com/Dreamacro/clash) which supports fake DNS would do your favor.

DNS module included fake DNS support was deprecated in previous version since it should not be tun2socks’ job to handle.

**Comment by Lingxi-Li** [comment]
@xjasonlyu , fake DNS should fall within scope. I see the name `tun2socks` as transparently redirecting traffic to a SOCKS5 proxy. SOCKS5 supports remote DNS resolution that is impossible without tricks like fake DNS. Adding this feature would make the SOCKS5 part complete.

**Comment by xjasonlyu** [comment]
SOCKS5 supports both local and remote DNS resolving, and I agree FakeDNS is a nice feature to have. 

For now, users can use proxy servers like clash/v2ray with fake dns support to enhance the experience.

**Comment by Lingxi-Li** [comment]
Clash's TUN mode falls flat on Windows with IP routing enabled (to achieve gateway proxy). Self-loop was monitored on Wireshark. I'm yet to experiment with v2ray.

That said, providing FakeDNS would give this project a huge edge over alternatives. Hope that gives you some motivation for this feature ask :grin:
