### ISSUE TITLE
关于代码编译的问题

### ISSUE THREAD

**Issue by ddiiccoo** [xjasonlyu/tun2socks#41]
首先非常感谢您提供了这么优秀的程序供我们学习、使用。这段时间我在试着编译您的V1版的tun2socks。我的编译方法如下：
在MinGW的编译环境下，进入go-tun2socks源代码的根目录，执行make命令进行编译。由于原版代码缺少了跟加密有关的几个库“函数的声明”，所以在core/c/custom/sys_arch.c文件里加入了个头文件声明#include <Wincrypt.h>，另外为了支持MinGW编译，在原来_WIN32宏定义的基础上加了__MINGW32__宏。这样，就可以编译出原版的可执行文件。
程序是编译出来了，但是编译出的EXE文件体积有3MB多。这倒是没关系。关键程序执行效率经测试远远没有您提供的编译版本v1.18.3高，几乎就没法用。请问是否我的编译过程不对？

**Comment by xjasonlyu** [comment]
V1版本的编译请看原版[eycorsican/go-tun2socks](https://github.com/eycorsican/go-tun2socks)，我没有在win下编译过。

**Comment by xjasonlyu** [comment]
我记得我好像改了点啥，不过当时v1就没打算在windows下面跑的，所以也没管了。。

**Comment by ddiiccoo** [comment]
哦，好的，谢谢
