### ISSUE TITLE
Support custom routes, exclude routes, DNS and MTU for Windows

### ISSUE THREAD

**Issue by kayrus** [xjasonlyu/tun2socks#42]
Hi, I'm working on a similar project fork (https://github.com/eycorsican/go-tun2socks). I [implemented](https://github.com/kayrus/go-tun2socks) some features I missed, but the upstream project is based on LwIP stack, which I don't like.

I'd happy to switch to your project, but it doesn't support features listed below:
* MTU set for Windows
* Custom routes (CLI arg)
* Exclude routes (CLI arg)
* DNS setting

I prepared a package to support this stuff: https://github.com/kayrus/tuncfg
It would be nice if you embed it into your project

**Comment by xjasonlyu** [comment]
> Hi, I'm working on a similar project fork (https://github.com/eycorsican/go-tun2socks). I implemented some features I missed, but the upstream project is based on LwIP stack, which I don't like.

The first version of this project was based on that too.

> I'd happy to switch to your project, but it doesn't support features listed below:
> 
> * MTU set for Windows
> * Custom routes (CLI arg)
> * Exclude routes (CLI arg)
> * DNS setting

I used to consider about tun2socks with built-in route table configuration support, but then I think it's unnecessary. Configuring with scripts would also be convenient and make tun2socks simpler.
