### ISSUE TITLE
[Feature] Don't send everything to the proxy

### ISSUE THREAD

**Issue by christianmerges** [xjasonlyu/tun2socks#430]
### Description

It would be great to not send everything to the proxy. Sometimes there are applications, who produce a lot of traffic, but don't have to be proxied. For an example it would be great to exclude youtube traffic from being sent to the proxy. Basically some kind of regex choosing if the request is send to wan, proxy1 or proxy2.

### Is this feature related to a specific bug?

no

### Do you have a specific solution in mind?

I thought about IPtables rules, but making these decisions on ip addresses is probably not right, because many websites share the same reverse proxy ips. So the decission shoul be made after, wenn the request is read.

**Comment by xjasonlyu** [comment]
I think it's something that should be configured on the proxy server, i.e. having ACL rules in the proxy and bypass youtube traffic. A lot of proxy servers are able to achieve this.

**Comment by christianmerges** [comment]
makes sense.
