### ISSUE TITLE
Forward TCP and UDP separately

### ISSUE THREAD

**Issue by hdid** [xjasonlyu/tun2socks#45]
Hi
Is it possible that forward TCP traffic to for example socks1:1080 and UDP to socks2:1081?
Because some proxies do not support udp but have good speed for tcp forwarding.
Thanks

**Comment by xjasonlyu** [comment]
Maybe you can use iptables to redirect separately.

**Comment by hdid** [comment]
I tried some tips but failed:
https://serverfault.com/questions/234370/forward-all-ports-incoming-to-a-specific-ip-to-internal-ip-address
https://serverfault.com/questions/690435/iptables-udp-port-forwarding

**Comment by xjasonlyu** [comment]
It seems like you need the OUTPUT chain.

**Comment by xjasonlyu** [comment]
https://unix.stackexchange.com/questions/85932/how-can-i-redirect-outbound-traffic-to-port-80-using-iptables-locally

I'm not sure if this would work.

**Comment by hdid** [comment]
Yeah did not work.

**Comment by xjasonlyu** [comment]
Technically, it’s not tun2socks’ job to do that, but proxy server’s. Maybe you just get your needs wrong at the first time.

**Comment by hdid** [comment]
Thanks for replies. I mostly liked this mode become an optional feature of tun2socks; arguments like -tcp-proxy and -udp-proxy that should be used together..
Thank you anyway ;)

**Comment by tormentous** [comment]
this is exactly what UDPGW is
