### ISSUE TITLE
能否实现应用进程规则的支持

### ISSUE THREAD

**Issue by ccwater666** [xjasonlyu/tun2socks#48]
就是假如我只希望curl的流量进入tun的话，就把curl这个名字配置进去就可以了。

**Comment by xjasonlyu** [comment]
這個你應該在系統中利用如cgroup來設置吧。

**Comment by ccwater666** [comment]
cgroups是特定于Linux内核的功能，因此在Mac上找不到。
有这个需求的主要原因是，我把tun的proxy 指向了本地的ss-local服务，tun设置了网关并设置成了默认网关，ss-local上添加了gfwlist.acl自动分流，这个时候访问google是没问题的，但是访问百度的时候，ss-local会把百度的流量又转到tun里面。导致环路了。如果可以设置ss-local的流量不再进入tun，走原来的路由器网关。就可以避免出现环路。或者有其它的解决方案吗？


sudo ./tun2socks-darwin-amd64 --device tun://utun123 -proxy socks5://127.0.0.1:1186 --interface en0

sudo ifconfig utun123 198.18.0.1 netmask 255.255.255.255 198.18.0.1 up

sudo route del default
sudo route add default 198.18.0.1
sudo route add ${proxy_server_ip} ${your_gateway}

**Comment by xjasonlyu** [comment]
有的，macos 和 linux 下都有綁定接口的操作，不過不知道 ss-local 有沒有這個東西。

**Comment by iosmanthus** [comment]
@ccwater666 如果单纯只是 curl 的话，curl 不是有 `--socks5` option 吗？
