### ISSUE TITLE
cannot make curl request for tun0

### ISSUE THREAD

**Issue by connected201** [xjasonlyu/tun2socks#54]
hi, i tried from Debian 10 and Ubuntu 20.04 
step to reproduce:
./tun2socks -device tun://tun0 -proxy socks5://127.0.0.1:9050
curl --interface tun0 https://api.myip.com
curl: (7) Couldn't connect to server
question: how to check if tun0 working? i started tor as proxy to check but not working
ip a:
14: tun0: <POINTOPOINT,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 500
    link/none
i cannot make to work tun0 driver
i tried in rasberry (armv7) and AMD64 (Debian 10)
In windows tun2socks works!.

![image](https://user-images.githubusercontent.com/20506433/120208626-5e3cd680-c236-11eb-93fb-7b82f57e69f7.png)

**Comment by xjasonlyu** [comment]
First, you need to configure route tables. Then, make sure there is no traffic loop on your local network.

**Comment by connected201** [comment]
> 
> 
> First, you need to configure route tables. Then, make sure there is no traffic loop on your local network.

can you give some example?

**Comment by xjasonlyu** [comment]
See [Wiki](https://github.com/xjasonlyu/tun2socks/wiki)

**Comment by connected201** [comment]
> 
> 
> See [Wiki](https://github.com/xjasonlyu/tun2socks/wiki)

in wiki nothing about route table!

**Comment by xjasonlyu** [comment]
https://github.com/xjasonlyu/tun2socks/wiki/Route-configuration

**Comment by connected201** [comment]
thanks. but i cannot set to work
my local ip for eth0 is 192.168.1.74
i tried this:
route add -net 192.168.1.74 netmask 255.255.255.0 tun0

ip route add 192.168.1.0/24 dev tun0
but, i'm newbie in linux, and don't know how to configure your great software (in windows works without loot of settings), thanks for help, best regards.
