### ISSUE TITLE
ipv6支持

### ISSUE THREAD

**Issue by fbion** [xjasonlyu/tun2socks#6]
fake dns 解析aaaa直接去backendDNS查询
考虑支持ipv6 fake dns吗

客户端直接访问ipv6地址时 程序也并没有处理？

sudo sysctl -w net.inet6.ip6.forwarding=1

客户端添加ipv6 dns,设置ipv6路由后 ，没有ipv6 fake dns也没用啊😂

**Comment by xjasonlyu** [comment]
我参考了Surge的实现方法，没有对AAAA记录的DNS请求做FakeDNS（实际上也没有必要），ipv6理论上就直接用upstream DNS做解析去了吧。

**Comment by fbion** [comment]
> 我参考了Surge的实现方法，没有对AAAA记录的DNS请求做FakeDNS（实际上也没有必要），ipv6理论上就直接用upstream DNS做解析去了吧。
upstream DNS如果返回了ipv6地址 客户端会去直连的 然而联不通...

**Comment by xjasonlyu** [comment]
啊对的（我没用ipv6所以没想到这个），我看了一下Surge在enhanced mode下也是只转发ipv4的流量，当时只想实现一个类似Surge的网关模式跑在linux里没想这么多😅

那你ipv6单独配置一个网关应该就行了，不走tun2socks

**Comment by fbion** [comment]
我的做法是 upstream DNS指向一个不存在的端口
