### ISSUE TITLE
Hiring for work on tun2socks

### ISSUE THREAD

**Issue by RuralDependencies** [xjasonlyu/tun2socks#60]
Good morning,

Sorry to add a feature request I'm just really interested to be able to reach you, I'm willing to sponsor you/hire you (good pay) for some work on this project (very basic).
I've sent you an email but lacking reply since 3 days.

Thank you Jason

**Comment by xjasonlyu** [comment]
You probably sent to a wrong address.

**Comment by RuralDependencies** [comment]
Thanks for the reply! 
I sent on this@12x.me, any other email I should use?

**Comment by xjasonlyu** [comment]
Oh sorry, it was detected as spam.

**Comment by xjasonlyu** [comment]
Check your email.
