### ISSUE TITLE
Socks4 statistics

### ISSUE THREAD

**Issue by chromer030** [xjasonlyu/tun2socks#61]
**Environment**
 - OS: Arch Linux
 - Version: Latest

**Describe the bug**
Statistics page just sends an hello !

`./tun2socks-linux-amd64 -device tun://tun0 -proxy $proxy -stats 127.0.0.1:8081`

![Screenshot_20210722_115055](https://user-images.githubusercontent.com/13361552/126620860-781cc694-d01a-4e29-8020-e08e4623cf81.jpg)

**Comment by xjasonlyu** [comment]
😂

**Comment by chromer030** [comment]
Am i doing something wrong ?

**Comment by xjasonlyu** [comment]
No, it's just what it supposed to send.

- `/`: hello page
- `/logs`: logs page
- `/connections`: connections page

```go
r.Group(func(r chi.Router) {
	r.Use(authenticator(token))
	r.Get("/", hello)
	r.Get("/logs", getLogs)
	r.Get("/traffic", traffic)
	r.Get("/version", version)
	r.Mount("/connections", connectionRouter())
})
```
