### ISSUE TITLE
I want to use "none" cipher with ShadowSocks

### ISSUE THREAD

**Issue by WinLinux1028** [xjasonlyu/tun2socks#65]
I want to use "none" cipher, but this doesn't support.
```
# ./tun2socks -proxy ss://none:(password)@(IP address):(port) -device tun0
FATA[0000] Failed to start engine: ss initialize: cipher not supported
```

**Comment by xjasonlyu** [comment]
Sorry, the shadowsocks [dependency](https://github.com/Dreamacro/go-shadowsocks2) used by tun2socks doesn't support `none` cipher yet.

**Comment by WinLinux1028** [comment]
I created a repository that merged [this](https://github.com/Dreamacro/go-shadowsocks2/pull/2) pull request.
https://github.com/WinLinux1028/go-shadowsocks2

**Comment by xjasonlyu** [comment]
> I created a repository that merged [this](https://github.com/Dreamacro/go-shadowsocks2/pull/2) pull request.
> https://github.com/WinLinux1028/go-shadowsocks2

Great, now you just have to pull request to the original repo and wait for merging.

**Comment by WinLinux1028** [comment]
I found "dummy" can use as "none".
Thank you.
