### ISSUE TITLE
[Feature Request] Support UDS and vsock

### ISSUE THREAD

**Issue by jackloomen** [xjasonlyu/tun2socks#68]
```
 -proxy string
    	Use this proxy [protocol://]host[:port]
```

Request for support where host[:port] is optionally a unix domain socket path.

socks5 being served over uds (ex. tor socks5 uds mode)

this will allow the creation of fully isolated network namespaces that have a tun0 interface forced through socks5 (over uds) and no other routing possible even with human error.

Request for support where host[:port] is optionally a vsock:cid:port serving socks5 from a host to a guest vm.
vm guest turns socks5 service provided over vsock by host

https://github.com/mdlayher/vsock

current workaround which involves additional latency and cpu cycles (additional userland<->kernel context switches) is socat:
http://www.dest-unreach.org/socat/doc/socat.html

**Comment by xjasonlyu** [comment]
Hi, does UDS+vsock support socks5/UDP transport?

**Comment by jackloomen** [comment]
> Hi, does UDS+vsock support socks5/UDP transport?

Both UDS and vsock have datagram variants, but I do not believe this should be relevant here because socks5 apparently makes UDP requests in the protocol itself - socks5 servers are not listening on UDP.

> When a client wants to relay UDP traffic over the SOCKS5 proxy, the client makes a UDP associate request over the TCP. SOCKS5 server then returns an available UDP port to the client to send UDP packages to.
> 
> Client then starts sending the UDP packages that needs to be relayed to the new UDP port that is available on SOCKS5 server. SOCKS5 server redirects these UDP packages to the remote server and redirects the UDP packages coming from the remote server back to the client.
> 
> When client wants to terminate the connection, it sends a FIN package over the TCP. The SOCKS5 server then terminates the UDP connection created for the client and then terminates the TCP connection.

https://stackoverflow.com/questions/14043348/how-can-i-send-udp-packets-over-socks-proxy


So while tor does indeed not support UDP that should not be your problem, the tor socks5 implementation will simply ignore "UDP associate requests" and to the user it will appear as all UDP traffic getting dropped. Should there be another socks5 implementation that supports UDS which handles UDP in accordance to the socks5 protocol then fine.

**Comment by xjasonlyu** [comment]
Correct, socks5 TCP implementation in UDS is feasible, but UDP support seems not quite possible.

Is there any SOCKS5 servers that support UDS except tor?

**Comment by jackloomen** [comment]
This appears like a niche usecase for a service which bridges socks5 locally to some remote location over a non-socks5 protocol. And is of a mind to support UDS. I'm aware of only tor. Though even services which don't support UDS natively can be redirected to UDS using third party software to achieve security via filesystem permissions.

The same can be also be done via tun2socks, native support would merely avoid additional overhead.

**Comment by xjasonlyu** [comment]
Let me see what I can do

**Comment by xjasonlyu** [comment]
I can't figure out how to enable UDS socks for tor in macOS, do you have any ideas?

**Comment by jackloomen** [comment]
My familiarity with Apple is non-existent, but I know the kernel is forked from some old BSD so it must have UDS and a brief search found this:

http://www.golangdevops.com/2021/01/27/uds-unix-domain-socket-packages/


Maybe it will help.

**Comment by xjasonlyu** [comment]
OK, I mean, is there any way to enable UDS for tor. I don't see any args or config or manual something...

**Comment by jackloomen** [comment]
Oh I misread my bad
It's in the torrc manual:
https://2019.www.torproject.org/docs/tor-manual.html.en

```
SOCKSPort unix:/path/to/uds  WorldWritable
ControlPort unix:/path/to/uds WorldWritable RelaxDirModeCheck
```

If this doesn't work this means the tor project doesn't support UDS on OSX.

**Comment by xjasonlyu** [comment]
Oh, I see.

**Comment by xjasonlyu** [comment]
Experimental socks5 over UDS support: https://github.com/xjasonlyu/tun2socks/commit/07ce5e64224fac62d5430ea9dbb6c474ab4ecf15
