### ISSUE TITLE
为何go get失败？

### ISSUE THREAD

**Issue by luckypoem** [xjasonlyu/tun2socks#7]
yudeMacBook-Air:gopath brite$ go get -u -v github.com/xjasonlyu/tun2socks/cmd/
github.com/xjasonlyu/tun2socks (download)
# cd .; git clone -- https://github.com/xjasonlyu/tun2socks /Users/brite/go1.13/go/gopath/src/github.com/xjasonlyu/tun2socks
Cloning into '/Users/brite/go1.13/go/gopath/src/github.com/xjasonlyu/tun2socks'...
fatal: unable to access 'https://github.com/xjasonlyu/tun2socks/': Server aborted the SSL handshake
package github.com/xjasonlyu/tun2socks/cmd: exit status 128
yudeMacBook-Air:gopath brite$

**Comment by xjasonlyu** [comment]
貌似是你的网络有问题，建议下载.zip再编译。

**Comment by briteming** [comment]
hi,

我挂了个vpn,go get成功：
yudeMacBook-Air:gopath brite$ go get -u -v github.com/xjasonlyu/tun2socks/cmd/
yudeMacBook-Air:gopath brite$ which cmd
/Users/brite/go1.13/go/bin/cmd
yudeMacBook-Air:gopath brite$ mv /Users/brite/go1.13/go/bin/cmd /Users/brite/go1.13/go/bin/tun2socks-by-xjasonlyu
yudeMacBook-Air:gopath brite$ cd ~
yudeMacBook-Air:~ brite$ sudo tun2socks-by-xjasonlyu -proxyServer 127.0.0.1:1080 -tunAddr 240.0.0.2 -tunGw 240.0.0.1 -tunName utun0
Password:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42e4c8a]

goroutine 1 [running]:
main.main()
	/Users/brite/go1.13/go/gopath/src/github.com/xjasonlyu/tun2socks/cmd/main.go:145 +0x4ba
yudeMacBook-Air:~ brite$

怎么解决？
