### ISSUE TITLE
Error DNS request

### ISSUE THREAD

**Issue by nodauf** [xjasonlyu/tun2socks#70]
**Environment**
 - OS: Archlinux 5.13
 - Version: tun2socks-2.3.0

**Log**
Paste the tun2socks log below with the log level set to `DEBUG`.
```
WARN[0086] [UDP] dial <ip>:53 error: client hanshake: 0X636F6D6D616E64206E6F7420737570706F72746564: command not supported 
```

**Describe the bug**
I have three devices. One windows (the one doing a DNS request), one linux (with chisel socks server), one windows (remote devices with chisel client)
When doing a DNS request to reach the remote network, the DNS request does not seem to go through the socks proxy. Each request give the error 
```
WARN[0086] [UDP] dial <ip>:53 error: client hanshake: 0X636F6D6D616E64206E6F7420737570706F72746564: command not supported 

```
Resolving the hostname from the linux does not work either

**To Reproduce**
1. Establish chisel connection between a client and a server
2. Add the routes
3. Send a dns request to the remote server

**Expected behavior**
The DNS request should go through the socks server

**Comment by xjasonlyu** [comment]
OK, after a little diagnosis, it looks like the socks5 module [`armon/go-socks5`](https://github.com/armon/go-socks5/blob/e75332964ef517daa070d7c38a9466a0d687e0a5/request.go#L247) used by chisel does not support UDP associate.

Ask chisel to support UDP via socks5 if needed.

**Comment by nodauf** [comment]
Ok thanks a lot to have looked

**Comment by connected201** [comment]
i have same error
![image](https://user-images.githubusercontent.com/20506433/132132368-725b3a4d-7476-4bc0-99de-548b59c6c2c2.png)
i tried with tor proxy, as i understand tor proxy don't support UDP, any solution to force requests to TCP ?

**Comment by xjasonlyu** [comment]
why do you need force requests to TCP?

**Comment by xjasonlyu** [comment]
the requests are made by your clients, if you want tun2socks to ignore UDP packet, use iptables.

**Comment by connected201** [comment]
i want to route all network traffic over TOR truth tun2socks, and i want to make all this with tun2socks
i tried this
ip tuntap add mode tun dev tun1
ip addr add 192.168.1.111/32 dev tun1
ip link set dev tun1 up
./tun2socks-linux-amd64 -device tun://tun1 -proxy socks5://127.0.0.1:9150
maybe need to make ip route replace default dev tun1 ?
i unable to make it to work

**Comment by xjasonlyu** [comment]
it’s unrelated to this issue lol, config route table see wiki.

**Comment by nodauf** [comment]
if anyone has the same issue with chisel. A pending PR works well (https://github.com/jpillora/chisel/pull/250/commits/cc9cbd1e6cbf56d7ae442b50138f387582879009). So definitely no issue with UDP and tun2socks
