### ISSUE TITLE
Support read from FileDescriptor

### ISSUE THREAD

**Issue by kaisar945** [xjasonlyu/tun2socks#71]
I don't know how to use this project in android please help me thanks

**Comment by xjasonlyu** [comment]
I'm not familiar with Android, but try to use tun instead of fd.

**Comment by nicolas-yangli** [comment]
> 
> 
> I'm not familiar with Android, but try to use tun instead of fd.

tun cannot be open(2) directly in android without root privilege, but an fd to tun can be obtained from android framework.

**Comment by kaisar945** [comment]
Thanks friend😄

**Comment by huqiyu** [comment]
Engine.stop() will report an error when restarted after disconnection 
GoLog: fdsan: attempted to close file descriptor 160, expected to be unowned, actually owned by ParcelFileDescriptor 0xe4afcec
