### ISSUE TITLE
http代理，dns包没有发给代理服务器

### ISSUE THREAD

**Issue by cnddy** [xjasonlyu/tun2socks#72]
环境 manjaro linux
启动命令 sudo ./tun2socks -proxy http://192.168.12.13:9080 -device tun0

问题是http代理是不支持udp的，但是图片上的信息显然是没有关闭udp，显示不支持，而且dns也没有发给代理服务器解析，怎么还在本地解析呢

**Comment by cnddy** [comment]
![IMG_20211001_220513](https://user-images.githubusercontent.com/86910496/135634725-d3165a6f-2d2e-4f80-a95f-04cec0b841a4.jpg)

**Comment by xjasonlyu** [comment]
用不支持udp的代理的时候，想要dns正常工作就需要路由表专门将dns ip给绕过tun接口了。
