### ISSUE TITLE
client handshake: 0x07: command not supported 

### ISSUE THREAD

**Issue by faquir-sun** [xjasonlyu/tun2socks#79]
**Environment**
 - OS: [`opwnwrt 19`]
 - Version: [`v2.3.2`]
 - Network: [route tables, iptables rules]
 - ip addr add 10.0.0.1/15 dev tun1
 - route add 0.0.0.0 mask 0.0.0.0 10.0.0.1
 - ./tun2socks-linux-amd64 -device tun://tun1 -proxy socks5://127.0.0.1:1080 -loglevel debug

1.chrome 打开网页没反应
2.ping www.google.com 没有任何反应
3.微信可以正常登陆

**Log**
```
WARN[3348] [UDP] dial 8.8.8.8:53 error: client handshake: 0x07: command not supported 
WARN[3348] [UDP] dial 8.8.8.8:53 error: client handshake: 0x07: command not supported 
WARN[3348] [UDP] dial 8.8.8.8:53 error: client handshake: 0x07: command not supported 
WARN[3349] [UDP] dial 8.8.4.4:53 error: client handshake: 0x07: command not supported 
WARN[3349] [UDP] dial 8.8.4.4:53 error: client handshake: 0x07: command not supported 
WARN[3349] [UDP] dial 8.8.4.4:53 error: client handshake: 0x07: command not supported 
WARN[3350] [UDP] dial 8.8.8.8:53 error: client handshake: 0x07: command not supported 
WARN[3350] [UDP] dial 8.8.8.8:53 error: client handshake: 0x07: command not supported 
WARN[3351] [UDP] dial 8.8.4.4:53 error: client handshake: 0x07: command not supported 
WARN[3351] [UDP] dial 8.8.4.4:53 error: client handshake: 0x07: command not supported 
WARN[3352] [UDP] dial 8.8.4.4:53 error: client handshake: 0x07: command not supported 
WARN[3352] [UDP] dial 8.8.4.4:53 error: client handshake: 0x07: command not supported 
WARN[3352] [UDP] dial 8.8.4.4:53 error: client handshake: 0x07: command not supported 
WARN[3354] [UDP] dial 8.8.4.4:53 error: client handshake: 0x07: command not supported 
WARN[3354] [UDP] dial 8.8.4.4:53 error: client handshake: 0x07: command not supported 
WARN[3354] [UDP] dial 8.8.8.8:53 error: client handshake: 0x07: command not supported 
WARN[3354] [UDP] dial 8.8.4.4:53 error: client handshake: 0x07: command not supported 
WARN[3355] [UDP] dial 8.8.8.8:53 error: client handshake: 0x07: command not supported 
```

**Comment by xjasonlyu** [comment]
你的proxy客户端是什么？

**Comment by faquir-sun** [comment]
客户端就是SS，是不是因为客户端不支持UDP协议导致的？

**Comment by xjasonlyu** [comment]
对啊，你没开UDP吧

**Comment by faquir-sun** [comment]
我想实现一个透明代理，连接openwrt的网络，所有流量通过socks出去，proxy以及客户端要满足什么要求？

**Comment by xjasonlyu** [comment]
> 我想实现一个透明代理，连接openwrt的网络，所有流量通过socks出去，proxy以及客户端要满足什么要求？

没看懂你的意思，透明代理就是transparent proxy，ss的客户端也支持的，openwrt也集成了。

**Comment by faquir-sun** [comment]
我是想用 tun2socks + proxy 实现类似openvpn的功能，实现全局流量通过socks。
tun2socks 支持 tcp、udp、icmp
那对proxy需要满足什么条件，才能达到我的目的。要支持TCP、UDP协议就可以了吗
比如我遇到的问题，是因为UDP没有开启，那ICMP协议是不是proxy支持了，才可以
我对网络不是很熟悉。感谢！

**Comment by xjasonlyu** [comment]
tun2socks由于是应用层转发所以并不支持ICMP，只是做了简单的echo reply。原则上proxy服务器最好支持TCP/UDP这样才能达到最好的效果，但也可以用iptables分流。

**Comment by faquir-sun** [comment]
您知道有哪些工具可以实现我的目的吗？openvpn可以实现我的目的但是感觉太重了，而且被墙的概率也比较大。

**Comment by xjasonlyu** [comment]
想要TCP/UDP/ICMP所有的支持，那只有完整的VPN才行，可以用ovpn，wireguard都可以。

**Comment by faquir-sun** [comment]
wireguard-go 这个是用户空间的实现，可以达到我的目的吗？还有就是我不知道如何将wireguard的流量转发到socks，在解决这个问题的过程中发现了tun2socks这个项目。

**Comment by xjasonlyu** [comment]
你到底是想要TCP/UDP/ICMP的流量转发，还是走SOCKS啊，前者只能VPN的，想要走socks那就是要么透明代理要么tun2socks了。

**Comment by faquir-sun** [comment]
根本目的是流量转发，不管走啥通道。就是想轻量级的。麻烦问一下，wireguard的流量怎么进行转发？不忙的话可以教教我吗

**Comment by xjasonlyu** [comment]
轻量级的就用代理就好了，wireguard/ovpn在大陆断流严重，wireguard不可以直接设置转发，ovpn可以通过代理转发不过效果不佳。

**Comment by faquir-sun** [comment]
wireguard的流量可通过IPtables 规则进行转发吗，ovpn客户端有配置可以通过代理转发，wireguard没发现 有这个功能

**Comment by xjasonlyu** [comment]
> wireguard的流量可通过IPtables 规则进行转发吗，ovpn客户端有配置可以通过代理转发，wireguard没发现 有这个功能

你可以用udptunnel转发

**Comment by faquir-sun** [comment]
好的，我试试，谢谢！

**Comment by masbur** [comment]
I had the same issue. I use SSH tunnel to get socks proxy. Do you know how to enable UDP in SSH ? or is there any option to turn off UDP in tun2socks ?

**Comment by xjasonlyu** [comment]
As far as I know, SSH tunnel cannot be configured to proxy UDP. And UDP cannot be turned off in tun2socks for now.

**Comment by connected201** [comment]
> tun2socks由于是应用层转发所以并不支持ICMP，只是做了简单的echo reply。原则上proxy服务器最好支持TCP/UDP这样才能达到最好的效果，但也可以用iptables分流。

really not support ICMP? on main page say that support
![image](https://user-images.githubusercontent.com/20506433/159063231-c5d3b487-dada-44ec-a6a9-047169e9daf7.png)
but why not working UDP for DNS?
![image](https://user-images.githubusercontent.com/20506433/159063471-ead2efb5-48b7-48bd-b8fe-66dd25510beb.png)

**Comment by xjasonlyu** [comment]
1. it says `ping echo` support, not icmp relay
2. it’s your proxy server doesn’t support UDP

**Comment by connected201** [comment]
so, i have these settings: i use tun2socks in windows, if i exclude from command `gateway=192.168.1.1 i` i cannot ping anything, but if i enable this parameter, ANY inexistend ip repli to ping, why?

```
start cmd /k tun2socks-windows-amd64.exe -device tun://tun0 -proxy socks5://127.0.0.1:6050
netsh interface ip set address "tun0" static address=192.168.1.1 mask=255.255.255.0 gateway=192.168.1.1
route add 192.168.0.0 mask 255.255.255.0 192.168.1.1
```

**Comment by v03413** [comment]
> tun2socks由于是应用层转发所以并不支持ICMP，只是做了简单的echo reply。原则上proxy服务器最好支持TCP/UDP这样才能达到最好的效果，但也可以用iptables分流。

作者您好，借楼请教一下；“处理来自本设备的任意网络应用的所有网络流量并通过代理转发”这句话能够理解为 支持代理转发所有网络层以上的所有流量吗？

---  

 因为我尝试用它代理 VPN PPTP 协议网络层的流量，但实际测试下来貌似并不可行。

**Comment by v03413** [comment]
> > tun2socks由于是应用层转发所以并不支持ICMP，只是做了简单的echo reply。原则上proxy服务器最好支持TCP/UDP这样才能达到最好的效果，但也可以用iptables分流。
> 
> 作者您好，借楼请教一下；“处理来自本设备的任意网络应用的所有网络流量并通过代理转发”这句话能够理解为 支持代理转发所有网络层以上的所有流量吗？
> 
> 因为我尝试用它代理 VPN PPTP 协议网络层的流量，但实际测试下来貌似并不可行。

如果是单纯VPN L2TP协议（基于TCP），那是可以正常拨号连接的；PPTP VPN里面含有部分  GRE  PPP协议的网络流量。

**Comment by xjasonlyu** [comment]
> 如果是单纯VPN L2TP协议（基于TCP），那是可以正常拨号连接的；PPTP VPN里面含有部分 GRE PPP协议的网络流量。

是的，准确的说是TCP/UDP/ICMP流量，因为绝大多数场景下都是以这三种流量为主的。

如果你想要PPTP的话，可以试试iptables把GRE包单独pass掉。

**Comment by v03413** [comment]
> > 如果是单纯VPN L2TP协议（基于TCP），那是可以正常拨号连接的；PPTP VPN里面含有部分 GRE PPP协议的网络流量。
> 
> 是的，准确的说是TCP/UDP/ICMP流量，因为绝大多数场景下都是以这三种流量为主的。
> 
> 如果你想要PPTP的话，可以试试iptables把GRE包单独pass掉。

好的，感谢解答；我还试着使用代理来代理PPTP看来不行。
