### ISSUE TITLE
请问如何处理使用本工具将本机流量转发到本机 SOCKS5 代理流量死循环的问题？

### ISSUE THREAD

**Issue by Loyalsoldier** [xjasonlyu/tun2socks#8]
本机运行着 SOCKS5 代理，想在本机使用本工具，将所有流量转发到本机的 SOCKS5 代理，但这流量形成死循环了，应该怎么处理？

**Comment by xjasonlyu** [comment]
本机的话，的确会死循环。。所以建议tun2socks跑在虚拟隔离环境里当网关用，暂时没考虑本机直接用的方案。
