### ISSUE TITLE
gVisor Potential Memory Leaking

### ISSUE THREAD

**Issue by avboy1337** [xjasonlyu/tun2socks#82]
**Environment**
 - OS: [e.g. `win server 2022`]
 - Version: [e.g. `v2.1.0`]
 - Network: [e.g. route tables, iptables rules]
 - Proxy Server: ssr

**Log**
Paste the tun2socks log below with the log level set to `DEBUG`.
```
```
![image](https://user-images.githubusercontent.com/5463104/145024631-42cd6868-ec13-44c9-8a1d-434982dae403.png)

**Comment by avboy1337** [comment]
![image](https://user-images.githubusercontent.com/5463104/145024787-a319450e-cf5c-4bcc-9e82-fe8ecea714d6.png)

**Comment by xjasonlyu** [comment]
没日志且版本不是最新，不清楚具体发生了什么

**Comment by avboy1337** [comment]
> 没日志且版本不是最新，不清楚具体发生了什么

tun2socks.exe -device tun://netch -proxy socks5://127.0.0.1:2801 -mtu 1500
ShadowsocksR.exe -s xx.xx.xx.xx -p 9880 -k 1hecCU -m rc4-md5 -t 120 -O origin -o http_simple --op download.windowsupdate.com -b 127.0.0.1 -l 2801
老哥方便加wx或者其他不？
avboy1337我的wx

**Comment by avboy1337** [comment]
版本用的最新的，自己编译的。另外，好像流量用多少，进程内存就增大多少。

**Comment by avboy1337** [comment]
最新的release，您编译的，没问题。目前最新的提交，commit的，自己编译的，会内存暴涨。

**Comment by xjasonlyu** [comment]
你试试最新的 8e00168914ffd9b8058ae22fa14bfbd19ec7b629 commit 还存在这个问题没有，我把依赖更新了一下

**Comment by xjasonlyu** [comment]
你自己编译的可以用`-version`看一下有没有编译对

**Comment by avboy1337** [comment]
D:\netch-1.9.4\Netch\bin\x64\Release\bin>tun2socks.exe -version
tun2socks-
windows/amd64, go1.17.3,

https://user-images.githubusercontent.com/5463104/145160336-92101009-3a03-4d1b-b9b7-28d1f2162bd5.mp4

**Comment by avboy1337** [comment]
version of lable 2.3.2 isok
the above video is compiled the latest commit

**Comment by xjasonlyu** [comment]
你拉一下新的最新的commit，然后用`make debug`编译，启动的时候在原启动命令后面加上`-stats :9000`这样。

运行一段时间，等内存上涨，然后浏览器进入[`http://127.0.0.1:9000/debug/pprof/`](http://127.0.0.1:9000/debug/pprof/)，看一下heap, allocs之类的信息，dump一些出来我再看看

**Comment by avboy1337** [comment]
if possible wx avboy1337

**Comment by f4nff** [comment]
好像确实存在内存泄露，
作者能不能把https://github.com/xjasonlyu/go-tun2socks精简一下，精简的跟https://github.com/xjasonlyu/tun2socks一样，
go-tun2socks有太多鸡肋，很多路由，dns不如使用脚本自己掌控，

**Comment by xjasonlyu** [comment]
哪个存在内存泄漏？go-tun2socks 已经不维护了。

**Comment by f4nff** [comment]
[tun2socks  ](https://github.com/xjasonlyu/tun2socks)    
这个，如果只是个人使用，比较难触发，如果挂在openwrt上面，长时间运行，能看出来，

**Comment by xjasonlyu** [comment]
你怎么看出来的，我自己是长期跑在docker里当旁路由的，没有什么问题。

**Comment by f4nff** [comment]
丢openwrt里面当主路由跑，
目前我跑的是自己git master的，现在跑你编译的v2.3.2试试

**Comment by xjasonlyu** [comment]
就内存占用高嘛没其他表现了？占用多少？

**Comment by f4nff** [comment]
一直在增长，昨天晚上400多，早上起来500多，

**Comment by f4nff** [comment]
其他倒是没什么，功能正常，

**Comment by f4nff** [comment]
目前测v2.3.2，但是也需要几天才能得出结论，如果你连接数少，可能触发进度比较慢吧，

**Comment by xjasonlyu** [comment]
🤔那我等下发你一个debug版本你去测一下？

**Comment by f4nff** [comment]
发

**Comment by xjasonlyu** [comment]
linux-amd64 版本的？

**Comment by f4nff** [comment]
arm64

**Comment by f4nff** [comment]
建议作者转向 https://github.com/shadowsocks/tun2socks  然后搞个功能跟你 这个一样的项目啊，
go 占用内存太大了。

**Comment by xjasonlyu** [comment]
我自己用的内存一般占用低于30MB

**Comment by f4nff** [comment]
那是你连接数太少了，

**Comment by f4nff** [comment]
```
root@ee:~/tun2socks/target/release# ./tun2socks
[2022-01-11T02:55:09Z INFO  tun2socks] tun device: name=utun9 address=10.192.168.10 gateway=10.192.168.1 network=10.192.168.0/24

Try:
    $ curl 180.101.49.12
    $ curl 172.217.25.78
    $ curl "10.192.168.10:80"
    $ curl "10.192.168.1:80"

    # macOS
    $ sudo route delete default; sudo route add default -interface utun9
    $ sudo route delete default; sudo route add default 192.168.199.1

[2022-01-11T02:55:09Z INFO  tun2socks] ready to go event loop...
```


把这个玩意搞一下，精简一下跟你现在一样的，

**Comment by xjasonlyu** [comment]
日常100+的connection

**Comment by f4nff** [comment]
go 的速度很快，但是占用cpu，内存太恐怖了

**Comment by f4nff** [comment]
反馈下，经过一天的测试，
最新的git拉取编译的**发现内存泄露**，
但是
https://github.com/xjasonlyu/tun2socks/releases/tag/v2.3.2
**没发现内存泄露**。

**Comment by avboy1337** [comment]
https://drive.google.com/file/d/1JYZ-laJzg-xHlnyI82YBs3nqAwi8G4Q2/view?usp=sharing
我用的这个软件。替换tun2socks后，可以看到视频里的效果。
需要自己有个ssr节点。

**Comment by avboy1337** [comment]
> 反馈下，经过一天的测试， 最新的git拉取编译的**发现内存泄露**， 但是 https://github.com/xjasonlyu/tun2socks/releases/tag/v2.3.2 **没发现内存泄露**。

我和你的结论一样。

**Comment by xjasonlyu** [comment]
[tun2socks-debug-linux-amd64.zip](https://github.com/xjasonlyu/tun2socks/files/7847601/tun2socks-debug-linux-amd64.zip)
[tun2socks-debug-linux-arm64.zip](https://github.com/xjasonlyu/tun2socks/files/7847602/tun2socks-debug-linux-arm64.zip)
[tun2socks-debug-win-amd64.zip](https://github.com/xjasonlyu/tun2socks/files/7847603/tun2socks-debug-win-amd64.zip)

**Comment by xjasonlyu** [comment]
你用上面对应的这个版本试试，我本地复现不了诶。

启动的时候在原命令后面加上`-stats :9000`，运行一段时间，等内存上涨，然后浏览器进入`http://[你的tun2socks机器ip]:9000/debug/pprof/`，有的dump之类的选项，导出来上传我看看🤔

**Comment by f4nff** [comment]
[gddx.zip](https://github.com/xjasonlyu/tun2socks/files/7848139/gddx.zip)

`dns -sr gddx.txt -at google.com -sl 6`

你执行这个试试看，我这边环境是arm64的，

**Comment by f4nff** [comment]
作者编译的debug版本好像没发现问题，

**Comment by f4nff** [comment]
tun2socks-debug-linux-arm64.zip

又出现了内存泄露。
```


Count | Profile
-- | --
482 | allocs
0 | block
0 | cmdline
110 | goroutine
482 | heap
0 | mutex
0 | profile
16 | threadcreate
0 | trace

```
[threadcreate.txt](https://github.com/xjasonlyu/tun2socks/files/7891124/threadcreate.txt)
[allocs.txt](https://github.com/xjasonlyu/tun2socks/files/7891127/allocs.txt)
[goroutine.txt](https://github.com/xjasonlyu/tun2socks/files/7891128/goroutine.txt)
[full goroutine stack dump.txt](https://github.com/xjasonlyu/tun2socks/files/7891129/full.goroutine.stack.dump.txt)
[heap.txt](https://github.com/xjasonlyu/tun2socks/files/7891130/heap.txt)

**Comment by f4nff** [comment]
问题告诉出现在：heap 上面。

**Comment by Windendless** [comment]
按照clash那边的issue的反馈，问题可能出在gvisor上

**Comment by f4nff** [comment]
gvisor
最近更新了很多，可以编译更新库试试，

**Comment by xjasonlyu** [comment]
应该是的，别的地方代码基本没变

**Comment by f4nff** [comment]
作者更新下库，编译个丢出来，一会我测测，

**Comment by xjasonlyu** [comment]
[tun2socks.zip](https://github.com/xjasonlyu/tun2socks/files/7896830/tun2socks.zip)

@f4nff 你试试

**Comment by f4nff** [comment]
tun2socks-debug-linux-arm64.zip
我要这个版本，

**Comment by xjasonlyu** [comment]
[tun2socks-debug-linux-arm64.zip](https://github.com/xjasonlyu/tun2socks/files/7896856/tun2socks-debug-linux-arm64.zip)
@f4nff

**Comment by f4nff** [comment]
@xjasonlyu   你最后编译这个，直接没法用了，

**Comment by xjasonlyu** [comment]
啊？报错了么？…

**Comment by f4nff** [comment]
没任何报错，也没任何数据传输，我刚才自己git了一下，跟你编译的一样，完全无法使用了

**Comment by xjasonlyu** [comment]
你开了log也没有任何输出吗…🤔（怕不是gVisor改了啥API不会…）

**Comment by f4nff** [comment]
你自己试试，

**Comment by avboy1337** [comment]
我现在没管这些，仍旧用的没问题的那个release版本，自己编译的。我怀疑是后面引入了bug。目前问题是，大家都没空去整理。我不会go。

**Comment by avboy1337** [comment]
不过我觉得可以测试出来，是哪个commit引起的问题

**Comment by Windendless** [comment]
gvisor v0.0.0-20211124014810-d07633871257，在macOS 11.6系统下貌似还存在内存泄漏的情况。

**Comment by f4nff** [comment]
ss不支持"none" 

`ssserver -k "" -m "none" -s "127.0.0.1:9000"`

https://github.com/shadowsocks/shadowsocks-rust

不支持此模式。

**Comment by f4nff** [comment]
最新版本，git依然存在内存泄漏，

**Comment by xjasonlyu** [comment]
> ss不支持"none"
> 
> `ssserver -k "" -m "none" -s "127.0.0.1:9000"`
> 
> https://github.com/shadowsocks/shadowsocks-rust
> 
> 不支持此模式。

本项目用的是go-shadowsocks2，所以它不支持none模式

**Comment by xjasonlyu** [comment]
> 最新版本，git依然存在内存泄漏，

正在更新gVisor到最新版，还在调试

**Comment by f4nff** [comment]
@xjasonlyu  老板增加个ws协议呀，然后再加个负载均衡，其他那些都可以不要了，

**Comment by Windendless** [comment]
> @xjasonlyu 老板增加个ws协议呀，然后再加个负载均衡，其他那些都可以不要了，

麻烦不要讨论和这个issue无关的内容

**Comment by f4nff** [comment]
@Windendless
噢噢噢噢

**Comment by avboy1337** [comment]
等调试完我再尝试下

**Comment by avboy1337** [comment]
仍旧没有修复上。有什么需要做的，请留言下，我尽量跟着调试下上传文件。

**Comment by xjasonlyu** [comment]
> 仍旧没有修复上。有什么需要做的，请留言下，我尽量跟着调试下上传文件。

这个问题相关commit我还没有提交

**Comment by avboy1337** [comment]
> > 仍旧没有修复上。有什么需要做的，请留言下，我尽量跟着调试下上传文件。
> 
> 这个问题相关commit我还没有提交

OKOK，等待老哥更新。确实非常期待！！我还在用2.3.2

**Comment by xjasonlyu** [comment]
> @xjasonlyu 你最后编译这个，直接没法用了，

Ref: https://github.com/google/gvisor/issues/7125

**Comment by xjasonlyu** [comment]
> 仍旧没有修复上。有什么需要做的，请留言下，我尽量跟着调试下上传文件。

你可以试试最新的commit

**Comment by avboy1337** [comment]
> > 仍旧没有修复上。有什么需要做的，请留言下，我尽量跟着调试下上传文件。
> 
> 你可以试试最新的commit

测试了下，仍旧会暴涨内存。我需要编译一个debug版本的。然后给老哥个报告。

**Comment by xjasonlyu** [comment]
Windows下吗，你怎么编译的，用`make debug`编译就好了。理论上这个版本的gVisor已经修复了内存泄漏问题了。

**Comment by avboy1337** [comment]
> Windows下吗，你怎么编译的，用`make debug`编译就好了。理论上这个版本的gVisor已经修复了内存泄漏问题了。

编译：
debug: BUILD_TAGS += debug
debug:
	$(GO_BUILD) -o $(BUILD_DIR)/$(BINARY)-$@
	GOARCH=amd64 GOOS=windows $(GO_BUILD) -o $(BUILD_DIR)/$(BINARY)-$@.exe
我直接在后面添加了上面这句话。然后make debug

运行命令如下：
"D:\netch-1.9.4\Netch\bin\x64\Release\bin\tun2socks.exe" -device tun://netch -proxy socks5://127.0.0.1:2801 -mtu 1500 -stats 9000
但是http://127.0.0.1:9000/没有回显

**Comment by xjasonlyu** [comment]
跑了一下，在最新commit测试中（Linux，AMD64平台）：

`TCP`：100+连接一共传输10G的数据，高峰内存占用达到800MB（gVisor本身实现即如此，正常现象），传输完成后五分钟后内存占用恢复到50MB以内，没有发现内存泄漏。

`UDP`：100+ PacketConn 传输10G数据，高峰内存占用达到70MB，传输完成后五分钟后内存占用恢复到50MB以内，也没有发现内存泄漏。

综上，个人认为至少Linux下的 Memory Leak 已经解决了。

**Comment by f4nff** [comment]
我也挂着测试了，

**Comment by f4nff** [comment]
[Chore: fix lint](https://github.com/xjasonlyu/tun2socks/commit/faed47da4015d2ca9c806168361e59cd8daa7423)

这个版本目前测试良好，内存占用，回收释放，暂时没发现问题。

**Comment by xjasonlyu** [comment]
连接数多，到900MB的占用是正常的，能释放掉就好了

**Comment by f4nff** [comment]
不正常，这才几个连接，你测试下ipv6

**Comment by xjasonlyu** [comment]
测了一下其他平台似乎还是存在内存泄漏

**Comment by f4nff** [comment]
肯定不正常，触发条件未知，

**Comment by xjasonlyu** [comment]
@avboy1337 你可以试试最新的commit，我本地测试没问题了

**Comment by f4nff** [comment]
还是存在内存泄露，
`/root/socks/tun -device tun1 -proxy socks5://[::1]:1080 -loglevel silent`
ipv6环境下，播放youtube视频，内存一直递增。
<img width="363" alt="image" src="https://user-images.githubusercontent.com/19538878/152157078-e82974a9-d92a-4b74-8e3e-cb136683c8db.png">
<img width="651" alt="image" src="https://user-images.githubusercontent.com/19538878/152157116-6803ee9e-a387-4931-bd0c-d86a460612a7.png">
连接数不多，带宽也不高。

**Comment by f4nff** [comment]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/19538878/152157864-421ebea6-6d05-49d6-890a-487e2ef1a30b.png">
`/root/socks/tun -device tun1 -proxy socks5://127.0.0.1:1080 -loglevel silent`
也是存在内存泄露。

**Comment by f4nff** [comment]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/19538878/152158113-f77a7212-2a9f-4931-87f5-3113130749c7.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/19538878/152158162-8f5b2475-5833-47cb-b154-967f4428c7ca.png">

`/root/socks/tun -device tun1 -proxy socks5://127.0.0.1:1080 -loglevel silent`

**Comment by f4nff** [comment]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/19538878/152159089-517c6e29-5383-48a8-8f40-a4dc7652fc0f.png">
纯ipv4环境，播放youtube 4k，一样如此。

**Comment by f4nff** [comment]
[2.3.2](https://github.com/xjasonlyu/tun2socks/releases/tag/v2.3.2)
版本就不会如此。

**Comment by xjasonlyu** [comment]
[tun2socks-debug.zip](https://github.com/xjasonlyu/tun2socks/files/7986643/tun2socks-debug.zip)

在启动命令后面加上`-stats 0.0.0.0:9000`，然后浏览器访问`http://<IP>:9000/debug/pprof/heap`，给一下结果

**Comment by f4nff** [comment]
[heap.zip](https://github.com/xjasonlyu/tun2socks/files/7986742/heap.zip)
<img width="355" alt="image" src="https://user-images.githubusercontent.com/19538878/152161480-d1f00ce1-82d3-416c-ac5f-22ffa6e815c2.png">

**Comment by f4nff** [comment]
泄露很明显。

**Comment by f4nff** [comment]
你这么一说，我想起来了，我这边youtube都是http3

**Comment by xjasonlyu** [comment]
[tun2socks-debug.zip](https://github.com/xjasonlyu/tun2socks/files/7986835/tun2socks-debug.zip)

@f4nff 你试试这个，应该就没有问题了。

**Comment by f4nff** [comment]
<img width="367" alt="image" src="https://user-images.githubusercontent.com/19538878/152164165-eb7ad4e3-1b5b-4e95-a0bd-bf4bdbb6ee61.png">
貌似确实好了，

**Comment by xjasonlyu** [comment]
嗯，那会儿UDP模块打算重构的，所以留着没修。

**Comment by f4nff** [comment]
我自己编译的也没问题了。

**Comment by f4nff** [comment]
我挂几天看看，

**Comment by avboy1337** [comment]
我立刻测，然后回复。

**Comment by avboy1337** [comment]
> 嗯，那会儿UDP模块打算重构的，所以留着没修。

屌爆了，修复了！！

**Comment by avboy1337** [comment]
老哥，问题好像恢复了。
麻烦老哥了。对不起。

**Comment by xjasonlyu** [comment]
> 老哥，问题好像恢复了。 麻烦老哥了。对不起。

没事，有问题是正常的。麻烦你重开一个issue，然后描述一下具体细节吧。
