### ISSUE TITLE
Does it support Android?

### ISSUE THREAD

**Issue by Eight-tail-cat** [xjasonlyu/tun2socks#87]
Android可以使用吗？可以的话，希望开发者编译一下，我不会ndk

**Comment by xjasonlyu** [comment]
不是很清楚安卓的环境，但是理论上用linux-arm64应该就可以了？（我不确定你可以试试）

**Comment by Eight-tail-cat** [comment]
emmm~~不行的，俺试了，俺不会ndk编译，应该编译一下就可以了

**Comment by xjasonlyu** [comment]
之前就有人在安卓上用，不过是他自己编译的而已，在其他issue里有

**Comment by Eight-tail-cat** [comment]
有ID没我去看看

**Comment by xjasonlyu** [comment]
#71 不过后续没人feedback 了

**Comment by Eight-tail-cat** [comment]
emm~好吧好吧，我再研究研究吧，你跟github那个badvpn有关系吗

**Comment by xjasonlyu** [comment]
没，之前用过但感觉不是很好用就自己写了这个

**Comment by Eight-tail-cat** [comment]
要是有Android就完美了，哈哈

**Comment by snltty** [comment]
有进展吗，我也有Andriod的需求

**Comment by crylg** [comment]
> 

是否解决，我也需要做个elf再安卓上使用

**Comment by Morrigan-Ship** [comment]
any solution for Android?
