### ISSUE TITLE
Socks4 support

### ISSUE THREAD

**Issue by chromer030** [xjasonlyu/tun2socks#9]
Hi , thanks for this great tool.
How we can use socks4 proxies via this tool ?
can any support be added ?

thanks again.

**Comment by xjasonlyu** [comment]
Socks4 protocol doesn't support UDP proxy, so it's not really useful.

**Comment by chromer030** [comment]
For some purposes that only TCP protocol matter , using socks4 is really great and the number of Socks4 proxies is very large than socks5.
if it's possible please add socks4 as an option.
Thank you.

**Comment by xjasonlyu** [comment]
Since SOCKS4 only support TCP protocol, you have to take DNS and other UDP traffic carefully while FakeDNS only works on A type record.

**Comment by chromer030** [comment]
For covering DNS we are using SOCKS 4A extensions ( remote hostname resolving feature ).

**Comment by xjasonlyu** [comment]
I know, that's what FakeDNS does, get your requested domain then forward via socks, but other DNS record type like `TXT` would fail.

**Comment by chromer030** [comment]
So isn't there any chance to have support it on tun2socks ???

**Comment by xjasonlyu** [comment]
Maybe later, I'll consider add socks4 as compatible proxy support when I have enough time.

**Comment by chromer030** [comment]
Great , Thank you very very much...

**Comment by chromer030** [comment]
Hi , any progress ? 🙏🙏🙏

**Comment by xjasonlyu** [comment]
Not yet.. Feel free to pull requests.
