### ISSUE TITLE
UDP Forwarding (udpgw)

### ISSUE THREAD

**Issue by tormentous** [xjasonlyu/tun2socks#90]
https://github.com/ambrop72/badvpn/wiki/Tun2socks

tun2socks can forward UDP, however this requires a daemon, badvpn-udpgw to run on the remote SSH server. To enable UDP forwarding:

On the remote SSH server, start: badvpn-udpgw --listen-addr 127.0.0.1:7300
Add the following arguments to badvpn-tun2socks: --udpgw-remote-server-addr 127.0.0.1:7300

**Comment by xjasonlyu** [comment]
1. What’s your issue?
2. They’re different projects.

**Comment by tormentous** [comment]
> * What’s your issue?
> * They’re different projects.

Sorry, its a feature request.

**Comment by xjasonlyu** [comment]
I still don’t know what is your requested feature.

**Comment by tormentous** [comment]
> I still don’t know what is your requested feature. Can you provide more specific details?

as the title says UDP Forwarding (udpgw)
in SSH Tunneling, this is necessary for VoIP (Voice and Video call) which uses UDP.
eg: say, the VoIP sever runs in port 7300, a UDP listener must be active for it to receive requests.

**Comment by xjasonlyu** [comment]
SSH tunnel doesn’t support UDP, however, if you want to forward UDP, use proper proxy server. 

Alternatively, you can try UDP over SSH, which transports both UDP/TCP in SSH tunnel.

**Comment by tormentous** [comment]
> > tun2socks can forward UDP, however this requires a daemon, badvpn-udpgw to run on the remote SSH server.
> 
> It’s SSH tunnel that doesn’t support UDP. So, if you want to forward UDP, use proper proxy server.
> 
> Alternatively, you can try UDP over SSH, which transports both UDP/TCP in SSH tunnel.

I was able to forward udp through badvpn tun2socks, not discrediting their work, your implementation is faster. ;) Thats why I asked for such feature… that is if you will grant it. Thanks in advance!

**Comment by tormentous** [comment]
Sorry for the bump, but this uspgw is also used for shadowsocks
https://gist.github.com/rsanden/ba29b8ea7d5d3bd482e717413a745243

**Comment by Masood-Lapeh** [comment]
Does this project support badvpn-udpgw or anything similar inorder to also forward UDP traffics via putty to openssh server? If not what ssh client/server supports UDP traffics?
