### ISSUE TITLE
time="2022-01-02T18:54:27+08:00" level=fatal msg="Failed to start engine: empty proxy"

### ISSUE THREAD

**Issue by zhao123gg** [xjasonlyu/tun2socks#91]
time="2022-01-02T18:54:27+08:00" level=fatal msg="Failed to start engine: empty proxy"

**Comment by xjasonlyu** [comment]
As it says, empty proxy..

**Comment by zhao123gg** [comment]
He now says wintun DLL error

**Comment by xjasonlyu** [comment]
But you didn’t provide enough info

**Comment by zhao123gg** [comment]
Error loading wintun.dll DLL: Unable to load library: The specified module could not be found.

[Redirector][aio_dial][udpPass] goroutine
1 [running]:
[Redirector][aio_dial][udpMeth] golang.zx2c4.com/wireguard/tun/wintun.(*lazyProc).Addr(...)
        golang.zx2c4.com/wireguard@v0.0.0-20211030003956-52704c4b9288/tun/wintun/dll_windows.go:
58
golang.zx2c4.com/wireguard/tun/wintun.CreateAdapter[Redirector][aio_dial][clrName] DONE({0xc0000200d6, 0x28}, {0xf6a1b6, 0x9
}, 0x0)
        golang.zx2c4.com/wireguard@v0.0.0-20211030003956-52704c4b9288/tun/wintun/wintun_windows.go:90 +0x1a5
[golang.zx2c4.com/wireguard/tun.CreateTUNWithRequestedGUIDR(e{0xc0000200d6, 0xb}, 0x0, 0x5dc)
        golang.zx2c4.com/wireguard@v0.0.0-20211030003956-52704c4b9288/tun/tun_windows.go:71 +0x46
dgolang.zx2c4.com/wireguard/tun.CreateTUN(...)
i       golang.zx2c4.com/wireguard@v0.0.0-20211030003956-52704c4b9288/tun/tun_windows.go:63
github.com/xjasonlyu/tun2socks/core/device/tun.Open({0xc0000200d6, 0x5}, 0x5dc)
        github.com/xjasonlyu/tun2socks/core/device/tun/tun_wireguard.go:30 +0x98
rgithub.com/xjasonlyu/tun2socks/engine.parseDevice({0xc0000200d0, 0xb}, 0x0)
        github.com/xjasonlyu/tun2socks/engine/parse.go:33ec +0x15f
github.com/xjasonlyu/tun2socks/engine.(*engine).setDevice(0x1294880)
        github.com/xjasonlyu/tun2socks/engine/engine.go:151 +0x3a
tgithub.com/xjasonlyu/tun2socks/engine.(*engine).start(0xc00004deb0)
        github.com/xjasonlyu/tun2socks/engine/engine.go:74 +0x218
github.com/xjasonlyu/tun2socks/engine.Start()
        github.com/xjasonlyu/tun2socks/engine/engine.go:20 +0x25
omain.main.func1(r{0xf6bba2, 0xc}, 0x1e70d870108)
        ]github.com/xjasonlyu/tun2socks/main.go[:33 +0x2aa
imain.maino()
        github.com/xjasonlyu/tun2socks/main.go:38 +0x7d

**Comment by xjasonlyu** [comment]
你wintun.dll下了吗

**Comment by zhao123gg** [comment]
> 你wintun.dll下了吗
等等哈 我发你代码

**Comment by zhao123gg** [comment]
> 你wintun.dll下了吗

private void CheckDriver()
        {
            var f = $@"{Environment.SystemDirectory}\wintun.dll";
            try
            {
                if (File.Exists(f))
                {
                    Log.Information($"Remove unused \"{f}\"");
                    File.Delete(f);
                }
            }
            catch
            {
                // ignored
            }
        }

**Comment by zhao123gg** [comment]
好了 谢谢 因为wintun代码写错了
