### ISSUE TITLE
启用后没法使用v2rayn的域名分流功能

### ISSUE THREAD

**Issue by yang05051** [xjasonlyu/tun2socks#94]
```
start cmd /k tun2socks-windows-amd64.exe -device tun://tun00 -proxy $Proxy
netsh interface ip set address "tun00" static address=10.10.10.2 mask=255.255.255.0 gateway=10.10.10.1
netsh interface ip set dns name="tun00" static 8.8.8.8
route add $ip $DefaultGateway metric 5
route add 0.0.0.0 mask 0.0.0.0 10.10.10.1
```

这个是我使用的配置tun2socks的cmd命令

运行之后可以正常上网，但是在v2rayn的log里面全是类似于 `104.16.16.16 [udp -> proxy]` 的记录，不能呈现域名

也就是说，tun2socks所创建的网卡帮我完成了域名解析，而不是交给v2rayn解析，导致了v2rayn无法识别正在访问的域名，只能识别我所连接到的IP（大部分是cloudflare的IP），无法完成域名分流

我尝试过不分配DNS给tun网卡，会导致无法上网

请问我应如何操作才能使v2rayn接管域名解析而完成域名分流？

另：连接到的为 vless 节点，使用了cloudflare的自选IP

**Comment by xjasonlyu** [comment]
目前为止，v2ray没有类似remote-dns/fake-dns的功能，所以无法在网络层转换就做到域名接管。

日后本项目计划加入内置fake-dns功能，到时候可以直接将域名交由上层代理工具解析。

目前你可以考虑使用类似clash的工具，可以达到你的需求。

**Comment by yang05051** [comment]
> 目前为止，v2ray没有类似remote-dns/fake-dns的功能，所以无法在网络层转换就做到域名接管。
> 
> 日后本项目计划加入内置fake-dns功能，到时候可以直接将域名交由上层代理工具解析。
> 
> 目前你可以考虑使用类似clash的工具，可以达到你的需求。

明白了，谢谢 😃

**Comment by MyNanyh** [comment]
现在可以实现了吗1

**Comment by MyNanyh** [comment]
tun2socks会把域名解析为IP，[TCP] 198.18.0.1:43824 <-> 64.233.185.188:5228，如何禁止解析
