### ISSUE TITLE
TCP SYN packets with ECN flag cannot be handled

### ISSUE THREAD

**Issue by mmmdbybyd** [xjasonlyu/tun2socks#95]
TCP的SYN包带有CWR ECN标志无法处理，以下为附件
![()`Y5G{N)JV2GIQ PC`GHDX](https://user-images.githubusercontent.com/18487473/149059920-58c4c922-6cea-48c6-96d2-a350c95ce716.jpg)

**Comment by xjasonlyu** [comment]
呃，你能不能提供一下这个问题的复现方法？

**Comment by mmmdbybyd** [comment]
我也不清楚如何复现，这个是我部分用户的手机出现这样的问题，我发现badvpn的tun2socks和另外一个gotun2socks并没有问题，可能是gvisor的问题

**Comment by xjasonlyu** [comment]
确认了，是gVisor的问题：[0b81b32c95f6643936d0894671d0b00809fe22d6](https://github.com/google/gvisor/commit/0b81b32c95f6643936d0894671d0b00809fe22d6#diff-a9c56024feff0c5dba6c358dc709f986231745922bd0b7cb2f358bf7b20ab727)，在下次更新gVisor的时候会修复。
